// Sound library names. Sample bytes are not stored here.
// tools/pcsrc.py reads ref/ at build time. The editor decodes a picked folder to audition.

export const PC_LIBRARY = {
  wolf: [
    "HITWALL", "SELECTWPN", "SELECTITEM", "HEARTBEAT", "MOVEGUN2", "MOVEGUN1",
    "NOWAY", "NAZIHITPLAYER", "SCHABBSTHROW", "PLAYERDEATH", "DOGDEATH", "ATKGATLING",
    "GETKEY", "NOITEM", "WALK1", "WALK2", "TAKEDAMAGE", "GAMEOVER",
    "OPENDOOR", "CLOSEDOOR", "DONOTHING", "HALT", "DEATHSCREAM2", "ATKKNIFE",
    "ATKPISTOL", "DEATHSCREAM3", "ATKMACHINEGUN", "HITENEMY", "SHOOTDOOR", "DEATHSCREAM1",
    "GETMACHINE", "GETAMMO", "SHOOT", "HEALTH1", "HEALTH2", "BONUS1",
    "BONUS2", "BONUS3", "GETGATLING", "ESCPRESSED", "LEVELDONE", "DOGBARK",
    "ENDBONUS1", "ENDBONUS2", "BONUS1UP", "BONUS4", "PUSHWALL", "NOBONUS",
    "PERCENT100", "BOSSACTIVE", "MUTTI", "SCHUTZAD", "AHHHG", "DIE",
    "EVA", "GUTENTAG", "LEBEN", "SCHEIST", "NAZIFIRE", "BOSSFIRE",
    "SSFIRE", "SLURPIE", "TOT_HUND", "MEINGOTT", "SCHABBSHA", "HITLERHA",
    "SPION", "NEINSOVAS", "DOGATTACK", "FLAMETHROWER", "MECHSTEP", "GOOBS",
    "YEAH", "DEATHSCREAM4", "DEATHSCREAM5", "DEATHSCREAM6", "DEATHSCREAM7", "DEATHSCREAM8",
    "DEATHSCREAM9", "DONNER", "EINE", "ERLAUBEN", "KEIN", "MEIN",
    "ROSE", "MISSILEFIRE", "MISSILEHIT",
  ],
  doom: [
    "DPPISTOL", "DPSHOTGN", "DPSGCOCK", "DPSAWUP", "DPSAWIDL", "DPSAWFUL",
    "DPSAWHIT", "DPRLAUNC", "DPRXPLOD", "DPFIRSHT", "DPFIRXPL", "DPPSTART",
    "DPPSTOP", "DPDOROPN", "DPDORCLS", "DPSTNMOV", "DPSWTCHN", "DPSWTCHX",
    "DPPLPAIN", "DPDMPAIN", "DPPOPAIN", "DPSLOP", "DPITEMUP", "DPWPNUP",
    "DPOOF", "DPTELEPT", "DPPOSIT1", "DPPOSIT2", "DPPOSIT3", "DPBGSIT1",
    "DPBGSIT2", "DPSGTSIT", "DPBRSSIT", "DPSGTATK", "DPCLAW", "DPPLDETH",
    "DPPDIEHI", "DPPODTH1", "DPPODTH2", "DPPODTH3", "DPBGDTH1", "DPBGDTH2",
    "DPSGTDTH", "DPBRSDTH", "DPPOSACT", "DPBGACT", "DPDMACT", "DPNOWAY",
    "DPBAREXP", "DPPUNCH", "DPTINK", "DPBDOPN", "DPBDCLS", "DPITMBK",
    "DPGETPOW", "DPPLASMA", "DPBFG", "DPCACSIT", "DPCYBSIT", "DPSPISIT",
    "DPSKLATK", "DPCACDTH", "DPSKLDTH", "DPCYBDTH", "DPSPIDTH", "DPHOOF",
    "DPMETAL",
  ],
  dave: [
    "HITWALL", "FALLING", "OUCH", "WALKING", "JUMPING", "TREASURE",
    "GOTTROPHY", "EXPLOSION", "FLYING", "NEXTLEVEL", "TOJETPACK", "GOTSOMETHNG",
  ],
  keen: [
    "WLDWALKSND", "WLDBLOCKSND", "WLDENTERSND", "KEENWALKSND", "KEENBLOKSND", "KEENJUMPSND",
    "KEENLANDSND", "KEENDIESND", "GOTBONUSSND", "GOTITEMSND", "GOTPARTSND", "KEENFIRESND",
    "KEENPOGOSND", "POGOJUMPSND", "LVLDONESND", "GAMEOVERSND", "HISCORESND", "TELEPORTSND",
    "CHUNKSMASH", "GOINDOORSND", "BUMPHEADSND", "USEKEYSND", "CANNONFIRE", "SLAMSND",
    "CLICKSND", "CRYSTALSND", "PLUMMETSND", "EXTRAMANSND", "YORPBUMPSND", "KEENWLK2SND",
    "YORPBOPSND", "GETCARDSND", "DOOROPENSND", "YORPSCREAM", "GARGSCREAM", "GUNCLICK",
    "SHOTHIT", "TANKFIRE", "VORTSCREAM", "KEENCICLE", "KEENSLEFT",
  ],
};
