#!/usr/bin/env python3
"""Pack ui/menudot_sheet_edit.png into 6×4 hi-res colour-layer sprites.

Sheet is 96×21 (six 16×21 frames). Each frame becomes four 24×21 sprites,
brightest Pepto colour in front. Pixels are snapped to Pepto's VIC-II
palette (http://www.pepto.de/projects/colorvic/). build.bat runs this.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "ui" / "menudot_sheet_edit.png"
OUT = ROOT / "src" / "menu_cursor_spr.asm"
PREVIEW = ROOT / "ui" / "menudot_cursor_preview.png"

SPR_W = 24
SPR_H = 21
FRAMES = 6
LAYERS = 4

# Pepto VIC-II palette — http://www.pepto.de/projects/colorvic/
C64_NAMES = (
	"black", "white", "red", "cyan", "purple", "green", "blue", "yellow",
	"orange", "brown", "ltred", "dkgrey", "grey", "ltgreen", "ltblue", "ltgrey",
)
PEPTO_RGB = (
	(0x00, 0x00, 0x00),
	(0xFF, 0xFF, 0xFF),
	(0x68, 0x37, 0x2B),
	(0x70, 0xA4, 0xB2),
	(0x6F, 0x3D, 0x86),
	(0x58, 0x8D, 0x43),
	(0x35, 0x28, 0x79),
	(0xB8, 0xC7, 0x6F),
	(0x6F, 0x4F, 0x25),
	(0x43, 0x39, 0x00),
	(0x9A, 0x67, 0x59),
	(0x44, 0x44, 0x44),
	(0x6C, 0x6C, 0x6C),
	(0x9A, 0xD2, 0x84),
	(0x6C, 0x5E, 0xB5),
	(0x95, 0x95, 0x95),
)


def nearest_pepto(rgb: tuple[int, int, int]) -> int:
	best = 0
	best_d = 10**9
	for i, (cr, cg, cb) in enumerate(PEPTO_RGB):
		d = (rgb[0] - cr) ** 2 + (rgb[1] - cg) ** 2 + (rgb[2] - cb) ** 2
		if d < best_d:
			best_d = d
			best = i
	return best


def pack_sprite(grid: list[list[int]], ox: int, oy: int) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = ox + col * 8 + bit
				y = oy + row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def main() -> None:
	if not PNG.is_file():
		raise SystemExit(f"missing {PNG}")
	im = Image.open(PNG).convert("RGBA")
	w, h = im.size
	if w != 16 * FRAMES or h != SPR_H:
		raise SystemExit(f"expected {16 * FRAMES}x{SPR_H} sheet, got {w}x{h}")
	px = im.load()

	used: set[int] = set()
	for y in range(h):
		for x in range(w):
			r, g, b, a = px[x, y]
			if a < 16:
				continue
			used.add(nearest_pepto((r, g, b)))
	ordered = sorted(used, key=lambda i: -(sum(PEPTO_RGB[i])))
	if len(ordered) != LAYERS:
		names = [C64_NAMES[i] for i in ordered]
		raise SystemExit(f"expected {LAYERS} Pepto colours, got {len(ordered)}: {names}")

	c64_cols = ordered
	fw = w // FRAMES
	blobs: list[int] = []
	layer_grids: list[list[list[list[int]]]] = []
	for fi in range(FRAMES):
		x0 = fi * fw
		grids: list[list[list[int]]] = []
		for col in ordered:
			grid = [[0] * SPR_W for _ in range(SPR_H)]
			for y in range(SPR_H):
				for x in range(fw):
					r, g, b, a = px[x0 + x, y]
					if a >= 16 and nearest_pepto((r, g, b)) == col:
						grid[y][x] = 1
			grids.append(grid)
			blobs.extend(pack_sprite(grid, 0, 0))
		layer_grids.append(grids)

	preview = Image.new("RGBA", (SPR_W * FRAMES, SPR_H), (0, 0, 0, 0))
	pp = preview.load()
	for fi, grids in enumerate(layer_grids):
		for li in reversed(range(LAYERS)):
			rgb = PEPTO_RGB[c64_cols[li]]
			grid = grids[li]
			for y in range(SPR_H):
				for x in range(SPR_W):
					if grid[y][x]:
						pp[fi * SPR_W + x, y] = (*rgb, 255)

	col_bytes = ",".join(f"${c:02x}" for c in c64_cols)
	col_names = ", ".join(C64_NAMES[c] for c in c64_cols)
	lines = [
		"; Auto-generated by tools/gen_menu_cursor_sprites.py from ui/menudot_sheet_edit.png",
		f"CURSOR_SPR_COUNT\t= {LAYERS}",
		f"CURSOR_FRAMES\t= {FRAMES}",
		f"CURSOR_SPR_W\t= {SPR_W}",
		f"cursor_spr_cols\t!byte {col_bytes}\t; {col_names}",
		"",
		"menu_cursor_spr",
	]
	lines.extend(fmt_bytes(blobs))
	lines.append("")

	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	preview.save(PREVIEW)
	print(
		f"wrote {OUT.relative_to(ROOT)} {FRAMES}x{LAYERS} sprites "
		f"[{col_names}] + {PREVIEW.relative_to(ROOT)}"
	)


if __name__ == "__main__":
	main()
