#!/usr/bin/env python3
"""Pack ui/quaketitle.png: dark-grey hires bitmap + 5 white highlight sprites.

Grey → bitmap ink on the black bar. White → one 24×21 sprite per letter.
Prefers ui/quaketitle_edit.png when present. build.bat runs this.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "ui" / "quaketitle.png"
PNG_EDIT = ROOT / "ui" / "quaketitle_edit.png"
OUT = ROOT / "src" / "menu_title.asm"
PREVIEW = ROOT / "ui" / "quaketitle_preview.png"

IMG_W = 320
IMG_H = 21
BAR_ROWS = 3
BAR_H = BAR_ROWS * 8
BAR_COLS = 40
SPR_W = 24
SPR_H = 21
SPR_COUNT = 5
MERGE_GAP = 8
PAD_Y = (BAR_H - IMG_H) // 2


def classify(im: Image.Image) -> tuple[list[list[int]], list[list[int]]]:
	rgb = im.convert("RGB")
	w, h = rgb.size
	px = rgb.load()
	grey = [[0] * w for _ in range(h)]
	white = [[0] * w for _ in range(h)]
	for y in range(h):
		for x in range(w):
			r, g, b = px[x, y]
			if r + g + b < 24:
				continue
			if r >= 240 and g >= 240 and b >= 240:
				white[y][x] = 1
			else:
				grey[y][x] = 1
	return grey, white


def letter_boxes(grey: list[list[int]], white: list[list[int]]) -> list[tuple[int, int]]:
	h = len(grey)
	w = len(grey[0])
	occ = [False] * w
	for x in range(w):
		for y in range(h):
			if grey[y][x] or white[y][x]:
				occ[x] = True
				break
	runs: list[tuple[int, int]] = []
	x = 0
	while x < w:
		if occ[x]:
			x0 = x
			while x < w and occ[x]:
				x += 1
			runs.append((x0, x - 1))
		else:
			x += 1
	merged: list[tuple[int, int]] = []
	for x0, x1 in runs:
		if merged and x0 - merged[-1][1] - 1 <= MERGE_GAP:
			merged[-1] = (merged[-1][0], x1)
		else:
			merged.append((x0, x1))
	return merged


def pack_hires_cell(grid: list[list[int]], cx: int, cy: int) -> list[int]:
	out = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(8):
		b = 0
		py = cy * 8 + row
		for bit in range(8):
			px = cx * 8 + bit
			if 0 <= py < gh and 0 <= px < gw and grid[py][px]:
				b |= 0x80 >> bit
		out.append(b)
	return out


def pack_sprite(grid: list[list[int]], ox: int, oy: int) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = ox + col * 8 + bit
				y = oy + row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def pad_y(src: list[list[int]]) -> list[list[int]]:
	w = len(src[0])
	grid = [[0] * w for _ in range(BAR_H)]
	for y, row in enumerate(src):
		grid[PAD_Y + y] = row[:]
	return grid


def main() -> None:
	src = PNG_EDIT if PNG_EDIT.is_file() else PNG
	if not src.is_file():
		raise SystemExit(f"missing {PNG}")
	im = Image.open(src)
	if im.size != (IMG_W, IMG_H):
		raise SystemExit(f"{src.name}: expected {IMG_W}x{IMG_H}, got {im.size}")
	grey, white = classify(im)
	boxes = letter_boxes(grey, white)
	if len(boxes) != SPR_COUNT:
		raise SystemExit(f"expected {SPR_COUNT} letters, got {len(boxes)}: {boxes}")

	grey_g = pad_y(grey)
	white_g = pad_y(white)

	used_x = [x0 for x0, _x1 in boxes] + [x1 for _x0, x1 in boxes]
	left_col = min(used_x) // 8
	right_col = max(used_x) // 8
	title_cols = right_col - left_col + 1

	cells: list[int] = []
	for cy in range(BAR_ROWS):
		for cx in range(left_col, left_col + title_cols):
			cells.extend(pack_hires_cell(grey_g, cx, cy))

	spr_ox: list[int] = []
	sprites: list[int] = []
	xlo: list[int] = []
	xmsb = 0
	for i, (x0, x1) in enumerate(boxes):
		lw = x1 - x0 + 1
		if lw > SPR_W:
			raise SystemExit(f"letter {i} is {lw}px wide; max {SPR_W}")
		ox = x0 - (SPR_W - lw) // 2
		ox = max(0, min(ox, IMG_W - SPR_W))
		spr_ox.append(ox)
		sprites.extend(pack_sprite(white_g, ox, PAD_Y))
		vic_x = 24 + ox
		xlo.append(vic_x & 255)
		if vic_x >= 256:
			xmsb |= 1 << i

	prev = Image.new("RGB", (IMG_W, BAR_H), (0, 0, 0))
	pp = prev.load()
	for y in range(BAR_H):
		for x in range(IMG_W):
			if white_g[y][x]:
				pp[x, y] = (255, 255, 255)
			elif grey_g[y][x]:
				pp[x, y] = (68, 68, 68)
	prev.save(PREVIEW)

	lines = [
		f"; Auto-generated by tools/gen_menu_title.py from {src.name}",
		f"TITLE_SPR_COUNT\t= {SPR_COUNT}",
		f"MENU_TITLE_LEFT\t= {left_col}",
		f"MENU_TITLE_COLS\t= {title_cols}",
		f"MENU_TITLE_ROWS\t= {BAR_ROWS}",
		f"MENU_TITLE_PAD_Y\t= {PAD_Y}\t; px from bar top to bitmap/sprites",
		"",
		"title_spr_xmsb\t!byte " + f"${xmsb:02x}",
		"title_spr_x\t!byte " + ", ".join(f"${v:02x}" for v in xlo),
		"",
		"menu_title_data",
	]
	lines.extend(fmt_bytes(cells))
	lines.append("")
	lines.append("menu_title_spr")
	lines.extend(fmt_bytes(sprites))
	lines.append("")

	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	print(
		f"wrote {OUT.relative_to(ROOT)} letters={[(a, b, o) for (a, b), o in zip(boxes, spr_ox)]} "
		f"cols={left_col}+{title_cols} xmsb=${xmsb:02x} + {PREVIEW.relative_to(ROOT)}"
	)


if __name__ == "__main__":
	main()
