#!/usr/bin/env python3
"""Build src/menu_text.asm from control/credits/readthis txt files.

readthis.txt is split into screens on lines that are only '^'.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "menu_text.asm"
READTHIS = ROOT / "readthis.txt"

# label, source txt (no yellow title — body only)
SCREENS = (
	("control_text", ROOT / "control.txt"),
	("credits_text", ROOT / "credits.txt"),
	("order_text", ROOT / "order.txt"),
	("ending1_text", ROOT / "ending1.txt"),
	("ending2_text", ROOT / "ending2.txt"),
)


def esc_scr(s: str) -> str:
	"""Escape for ACME !scr \"...\"."""
	return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_blob_lines(label: str, lines: list[str]) -> list[str]:
	while lines and not lines[-1].strip():
		lines = lines[:-1]
	out = [f"{label}"]
	for line in lines:
		body = line if line.strip() else " "
		out.append(f'\t!scr "{esc_scr(body)}",0')
	out.append("\t!byte 0")
	out.append("")
	return out


def emit_blob(label: str, path: Path) -> list[str]:
	return emit_blob_lines(label, path.read_text(encoding="utf-8").splitlines())


def split_caret_pages(text: str) -> list[list[str]]:
	pages: list[list[str]] = []
	cur: list[str] = []
	for line in text.splitlines():
		if line.strip() == "^":
			pages.append(cur)
			cur = []
		else:
			cur.append(line)
	pages.append(cur)
	cleaned: list[list[str]] = []
	for p in pages:
		while p and not p[0].strip():
			p = p[1:]
		while p and not p[-1].strip():
			p = p[:-1]
		if p:
			cleaned.append(p)
	return cleaned


def emit_readthis() -> list[str]:
	if not READTHIS.is_file():
		raise SystemExit(f"missing {READTHIS}")
	pages = split_caret_pages(READTHIS.read_text(encoding="utf-8"))
	if not pages:
		raise SystemExit(f"{READTHIS.name} has no screens")
	if len(pages) > 255:
		raise SystemExit(f"{READTHIS.name} has {len(pages)} screens; max 255")
	out: list[str] = [f"READTHIS_PAGES = {len(pages)}", ""]
	labels = [f"readthis{i}_text" for i in range(1, len(pages) + 1)]
	for label, lines in zip(labels, pages):
		out.extend(emit_blob_lines(label, lines))
	out.append("readthis_lo")
	out.append("\t!byte " + ", ".join(f"<{n}" for n in labels))
	out.append("readthis_hi")
	out.append("\t!byte " + ", ".join(f">{n}" for n in labels))
	out.append("")
	return out


def main() -> None:
	out: list[str] = [
		"; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root",
		"; readthis.txt pages split on lines that are only '^'",
		"",
	]
	for label, path in SCREENS:
		if not path.is_file():
			raise SystemExit(f"missing {path}")
		out.extend(emit_blob(label, path))
	out.extend(emit_readthis())
	OUT.write_text("\n".join(out), encoding="utf-8")
	print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
	main()
