#!/usr/bin/env python3
"""Fuse optional relocatable AI code with each enemy pose/SFX payload."""

from __future__ import annotations

import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENEMY_DIR = ROOT / "enemies"
SIZES_OUT = ROOT / "src" / "enemy_sizes.asm"
DOS_NAMES = ["grunt", "knight", "rott", "scrag", "ogre", "shambl", "chthon", "zombie"]

MAGIC = b"QAI1"
HEADER_SIZE = 14
NO_ENTRY = 0xFFFF
ENEMY_BANK_MAX = 8192


def load_module(dos: str) -> tuple[bytes, list[int], list[int], int]:
    code_path = ENEMY_DIR / f"ai_{dos}.bin"
    rel_path = ENEMY_DIR / f"ai_{dos}.rel"
    if not code_path.is_file():
        return b"", [], [], NO_ENTRY
    if not rel_path.is_file():
        raise SystemExit(f"{code_path}: missing {rel_path.name}")
    meta = json.loads(rel_path.read_text(encoding="utf-8"))
    code = code_path.read_bytes()
    internal = [int(v) for v in meta.get("internal", [])]
    map_sites = [int(v) for v in meta.get("map", [])]
    entry = int(meta.get("entry", 0))
    if not code:
        raise SystemExit(f"{code_path}: empty")
    if entry < 0 or entry >= len(code):
        raise SystemExit(f"{rel_path}: entry {entry} outside {len(code)}-byte module")
    for kind, sites in (("internal", internal), ("map", map_sites)):
        for off in sites:
            if off < 0 or off + 1 >= len(code):
                raise SystemExit(f"{rel_path}: {kind} relocation {off} outside module")
    return code, internal, map_sites, entry


def main() -> None:
    sizes: list[int] = []
    for dos in DOS_NAMES:
        pose_path = ENEMY_DIR / f"{dos}.pose"
        if not pose_path.is_file():
            raise SystemExit(f"missing {pose_path}; run genenemies.py first")
        pose = pose_path.read_bytes()
        code, internal, map_sites, entry = load_module(dos)
        records_size = 2 * (len(internal) + len(map_sites))
        code_off = HEADER_SIZE + records_size
        pose_off = code_off + len(code)
        entry_off = NO_ENTRY if entry == NO_ENTRY else code_off + entry
        header = struct.pack(
            "<4sHHHHH",
            MAGIC,
            len(code),
            len(internal),
            len(map_sites),
            entry_off,
            pose_off,
        )
        records = b"".join(struct.pack("<H", code_off + off) for off in internal)
        records += b"".join(struct.pack("<H", code_off + off) for off in map_sites)
        payload = header + records + code + pose
        if len(payload) > ENEMY_BANK_MAX:
            raise SystemExit(f"{dos}: fused bank {len(payload)} > {ENEMY_BANK_MAX}")
        (ENEMY_DIR / f"{dos}.prg").write_bytes(struct.pack("<H", 0) + payload)
        sizes.append(len(payload))
        print(
            f"{dos}: bank={len(payload)} code={len(code)} pose={len(pose)} "
            f"reloc={len(internal)} map={len(map_sites)}"
        )

    SIZES_OUT.write_text(
        "; Generated by tools/genaibanks.py — fused AI/pose/SFX bank bytes\n"
        + "enemy_size_lo\t!byte " + ",".join(str(s & 0xFF) for s in sizes) + "\n"
        + "enemy_size_hi\t!byte " + ",".join(str((s >> 8) & 0xFF) for s in sizes) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {SIZES_OUT.relative_to(ROOT)} sizes={sizes}")


if __name__ == "__main__":
    main()
