#!/usr/bin/env python3
"""Export fixed resident GAME entry addresses used by streamed AI modules."""

from __future__ import annotations

import argparse
from pathlib import Path

from mkreloc import parse_labels

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "ai_game_syms.asm"

REQUIRED = [
    "enemy_chebyshev",
    "enemy_same_floor",
    "enemy_shot_clear",
    "enemy_enter_approach",
    "enemy_enter_attack",
    "enemy_enter_ogre_attack",
    "enemy_enter_knight_attack",
    "select_dodge_dir",
    "enemy_patrol_step",
    "enemy_face_player",
    "pick_attack_var",
    "pain_var_off",
    "floor_below_y",
    "div24u8",
    "rnd8",
    "take_damage",
    "play_sound",
    "spawn_ogre_grenade",
    "spawn_scrag_spit",
    "enemy_try_step",
    "gren_alloc",
    "gren_fill_slot",
    "ent_vert_world",
    "atan2_yaw",
    "SOUND_OGRE_OGDRAG",
    "pos_ok",
    "crush_kill",
    "crush_load_box",
    "point_in_box_xz",
    "player_overlaps_y",
    "frustum_hits",
    "draw_box",
]


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate streamed-AI GAME symbol include")
    ap.add_argument("--labels", default="game-ai.lbl")
    ap.add_argument(
        "--verify-labels",
        default=None,
        help="also require every exported address to match this label file",
    )
    args = ap.parse_args()
    path = Path(args.labels)
    if not path.is_file():
        path = ROOT / path
    labels = parse_labels(path)
    missing = [name for name in REQUIRED if name not in labels]
    if missing:
        raise SystemExit(f"{path}: missing AI symbols: {', '.join(missing)}")
    if args.verify_labels:
        verify_path = Path(args.verify_labels)
        if not verify_path.is_file():
            verify_path = ROOT / verify_path
        verify = parse_labels(verify_path)
        mismatch = [
            name
            for name in REQUIRED
            if name not in verify or verify[name] != labels[name]
        ]
        if mismatch:
            details = ", ".join(
                f"{name} ${labels[name]:04x}->"
                + (f"${verify[name]:04x}" if name in verify else "missing")
                for name in mismatch
            )
            raise SystemExit(f"{verify_path}: streamed-AI GAME symbol drift: {details}")
        print(f"Verified AI symbols against {verify_path}")
    lines = ["; Generated by tools/genaisymbols.py — fixed GAME entry addresses"]
    lines.extend(f"{name}\t= ${labels[name]:04x}" for name in REQUIRED)
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(REQUIRED)} symbols)")


if __name__ == "__main__":
    main()
