#!/usr/bin/env python3
"""Pack assets/enemies/enemylod.png into 8×8 LOD glyphs → src/enemylod.asm."""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PNG = ROOT / "assets" / "enemies" / "enemylod.png"
OUT = ROOT / "src" / "enemylod.asm"

CELL = 8
N_GLYPHS = 7  # strip width / 8


def bchunk(data: list[int], w: int = 8) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def glyph_bytes(im: Image.Image, col: int) -> list[int]:
    out = []
    for y in range(CELL):
        b = 0
        for x in range(CELL):
            if im.getpixel((col * CELL + x, y)) > 128:
                b |= 0x80 >> x
        out.append(b)
    return out


def main() -> None:
    im = Image.open(PNG).convert("L")
    w, h = im.size
    if w != N_GLYPHS * CELL or h != CELL:
        raise SystemExit(f"{PNG} is {w}x{h}, expected {N_GLYPHS * CELL}x{CELL}")

    data: list[int] = []
    for i in range(N_GLYPHS):
        data.extend(glyph_bytes(im, i))

    parts = [
        "; Auto-generated by tools/genenemylod.py — do not edit\n",
        f"; {PNG.name}: {N_GLYPHS} of {CELL}x{CELL}, index = ent_type\n",
        f"ENEMY_LOD_N\t= {N_GLYPHS}\n",
        "enemy_lod\n",
        bchunk(data),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
