#!/usr/bin/env python3
"""Export Grunt + Rottweiler walk frames → src/enemy_data.asm."""

from __future__ import annotations

import json
from math import sqrt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "editor" / "quake64.json"
OUT = ROOT / "src" / "enemy_data.asm"

WALK_START = 4
WALK_LEN = 4
NVERTS = 13
TYPES = ["Grunt", "Rottweiler"]


INV_SQRT2 = 1.0 / sqrt(2.0)


def s8(n: int) -> int:
    n = int(n)
    if n < -128 or n > 127:
        raise ValueError(f"vert coord out of signed byte range: {n}")
    return n & 0xFF


def signed_s8(b: int) -> int:
    b &= 0xFF
    return b - 256 if b >= 128 else b


def rot45_xz(gx: list[int], gz: list[int]) -> tuple[list[int], list[int]]:
    """Match editor yaw: x' = x c + z s, z' = -x s + z c, at 45° (c = s = 1/√2)."""
    gx45: list[int] = []
    gz45: list[int] = []
    for x_u, z_u in zip(gx, gz):
        x = signed_s8(x_u)
        z = signed_s8(z_u)
        gx45.append(s8(round((x + z) * INV_SQRT2)))
        gz45.append(s8(round((z - x) * INV_SQRT2)))
    return gx45, gz45


def bchunk(data: list[int], w: int = 13) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def export_type(enemy: dict) -> tuple[list[int], list[int], list[int], list[list[int]]]:
    lines = enemy["lines"]
    frames = enemy["frames"]
    if len(lines) != NVERTS:
        raise SystemExit(f"{enemy['name']}: expected {NVERTS} lines, got {len(lines)}")
    if len(frames) < WALK_START + WALK_LEN:
        raise SystemExit(f"{enemy['name']}: frames shorter than walk clip")
    gx: list[int] = []
    gy: list[int] = []
    gz: list[int] = []
    for fi in range(WALK_START, WALK_START + WALK_LEN):
        fr = frames[fi]
        if len(fr) != NVERTS:
            raise SystemExit(f"{enemy['name']} frame {fi}: bad vert count")
        for v in fr:
            gx.append(s8(v["x"]))
            gy.append(s8(v["y"]))
            gz.append(s8(v["z"]))
    return gx, gy, gz, lines


def main() -> None:
    doc = json.loads(DOC.read_text(encoding="utf-8"))
    by_name = {e["name"]: e for e in doc["enemies"]}
    parts = [
        "; Generated by tools/genenemies.py — do not edit",
        "; Walk clips 0..3 as signed bytes (runtime <<5 → 8.8)",
        "; gx45/gz45 = 45° yaw bake; gy shared",
        "ENEMY_NTYPES\t= 2",
        "ENT_GRUNT\t= 0",
        "ENT_ROTT\t= 1",
        "",
    ]
    all_edges = None
    for ti, name in enumerate(TYPES):
        if name not in by_name:
            raise SystemExit(f"missing enemy {name}")
        gx, gy, gz, lines = export_type(by_name[name])
        gx45, gz45 = rot45_xz(gx, gz)
        if all_edges is None:
            all_edges = lines
        elif lines != all_edges:
            # Shared skeleton expected; still export first type's edges
            print(f"warning: {name} edges differ from Grunt; using Grunt edges")
        prefix = "grunt" if ti == 0 else "rott"
        parts.append(f"; --- {name} ---")
        parts.append(f"{prefix}_gx")
        parts.append(bchunk(gx).rstrip())
        parts.append(f"{prefix}_gy")
        parts.append(bchunk(gy).rstrip())
        parts.append(f"{prefix}_gz")
        parts.append(bchunk(gz).rstrip())
        parts.append(f"{prefix}_gx45")
        parts.append(bchunk(gx45).rstrip())
        parts.append(f"{prefix}_gz45")
        parts.append(bchunk(gz45).rstrip())
        parts.append("")

    edge_bytes: list[int] = []
    assert all_edges is not None
    for a, b in all_edges:
        edge_bytes.append(int(a))
        edge_bytes.append(int(b))
    parts.append("enemy_edges")
    parts.append("\t!byte " + ",".join(str(b) for b in edge_bytes))
    parts.append("")
    # Lo/hi pointers for type select
    parts.append("enemy_gx_lo\t!byte <grunt_gx, <rott_gx")
    parts.append("enemy_gx_hi\t!byte >grunt_gx, >rott_gx")
    parts.append("enemy_gy_lo\t!byte <grunt_gy, <rott_gy")
    parts.append("enemy_gy_hi\t!byte >grunt_gy, >rott_gy")
    parts.append("enemy_gz_lo\t!byte <grunt_gz, <rott_gz")
    parts.append("enemy_gz_hi\t!byte >grunt_gz, >rott_gz")
    parts.append("enemy_gx45_lo\t!byte <grunt_gx45, <rott_gx45")
    parts.append("enemy_gx45_hi\t!byte >grunt_gx45, >rott_gx45")
    parts.append("enemy_gz45_lo\t!byte <grunt_gz45, <rott_gz45")
    parts.append("enemy_gz45_hi\t!byte >grunt_gz45, >rott_gz45")
    # Hand-tuned view-Z integer; CMP only — not derived from height at runtime
    parts.append("enemy_far_z\t!byte 13, 4\t\t; Grunt, Rott LOD gate (CAM_ZH)")
    parts.append("")

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
