#!/usr/bin/env python3
"""Pack assets/enemies/enemy_muzzle_0..2.png → src/enemy_muzzle.asm (zeromask)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from sprmask import (  # noqa: E402
    CELL,
    bchunk,
    load_fx_raw,
    pack_zeromask,
)

PNG_DIR = ROOT / "assets" / "enemies"
OUT = ROOT / "src" / "enemy_muzzle.asm"
N = 3


def main() -> None:
    parts = [
        "; Auto-generated by tools/genenemymuzzle.py — do not edit\n",
        "; zeromask: 8 occupancy bytes + nonzero payload (24×21 hi-res)\n",
        "; Distance LOD: 0 = near/large … 2 = far/small\n",
    ]
    sizes = []
    for i in range(N):
        raw = load_fx_raw(PNG_DIR / f"enemy_muzzle_{i}.png", OUT, f"spr_emuz_{i}")
        packed = pack_zeromask(raw)
        sizes.append(len(packed))
        parts.append(f"spr_emuz_{i}\n")
        parts.append(bchunk(packed))
        parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} packed {sizes} (was {N}×{CELL})")


if __name__ == "__main__":
    main()
