#!/usr/bin/env python3
"""Export Grunt + Rottweiler poses + clips → src/enemy_data.asm."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "editor" / "quake64.json"
OUT = ROOT / "src" / "enemy_data.asm"

NVERTS = 13
TYPES = ["Grunt", "Rottweiler"]
PREFIX = ["grunt", "rott"]

# Facing folds into the runtime rotate angle (ent_rotate: a = yaw − rot),
# so no pre-baked 45° tables are needed.


def clip_key(name: str) -> str:
    return str(name).rstrip("_").lower()


def clip_const(prefix: str, name: str) -> str:
    key = clip_key(name).upper()
    key = re.sub(r"[^A-Z0-9]+", "_", key).strip("_")
    return f"{prefix.upper()}_CLIP_{key}"


def find_walk_clip(enemy: dict) -> tuple[int, int]:
    clips = enemy.get("clips") or []
    preferred = {"Grunt": "prowl", "Scrag": "fly"}
    key = preferred.get(enemy["name"], "walk")
    for want in (key, "walk", "prowl", "fly"):
        for c in clips:
            if clip_key(c.get("name", "")) == want:
                return int(c["start"]), int(c["len"])
    raise SystemExit(f"{enemy['name']}: no walk/prowl/fly clip")


def s8(n: int) -> int:
    n = int(n)
    if n < -128 or n > 127:
        raise ValueError(f"vert coord out of signed byte range: {n}")
    return n & 0xFF


def bchunk(data: list[int], w: int = 13) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def export_type(enemy: dict) -> tuple[list[int], list[int], list[int], list[list[int]], list[dict], tuple[int, int]]:
    lines = enemy["lines"]
    frames = enemy["frames"]
    clips = enemy.get("clips") or []
    if len(lines) != NVERTS:
        raise SystemExit(f"{enemy['name']}: expected {NVERTS} lines, got {len(lines)}")
    if not frames:
        raise SystemExit(f"{enemy['name']}: no frames")
    walk = find_walk_clip(enemy)
    gx: list[int] = []
    gy: list[int] = []
    gz: list[int] = []
    for fi, fr in enumerate(frames):
        if len(fr) != NVERTS:
            raise SystemExit(f"{enemy['name']} frame {fi}: bad vert count")
        for v in fr:
            gx.append(s8(v["x"]))
            gy.append(s8(v["y"]))
            gz.append(s8(v["z"]))
    return gx, gy, gz, lines, clips, walk


def main() -> None:
    doc = json.loads(DOC.read_text(encoding="utf-8"))
    by_name = {e["name"]: e for e in doc["enemies"]}
    parts = [
        "; Generated by tools/genenemies.py — do not edit",
        "; All clips as signed bytes (runtime (g*trig)>>2 → 8.8)",
        "; Facing folds into ent_rotate (a = yaw − rot) — no 45° bake",
        "ENEMY_NTYPES\t= 2",
        "ENT_GRUNT\t= 0",
        "ENT_ROTT\t= 1",
        "",
    ]
    all_edges = None
    walk_starts: list[int] = []
    walk_lens: list[int] = []
    death_starts: list[int] = []
    death_lens: list[int] = []
    max_nframes = 0

    for ti, name in enumerate(TYPES):
        if name not in by_name:
            raise SystemExit(f"missing enemy {name}")
        gx, gy, gz, lines, clips, walk = export_type(by_name[name])
        walk_starts.append(walk[0])
        walk_lens.append(walk[1])
        death = None
        for c in clips:
            if clip_key(c.get("name", "")) == "death":
                death = (int(c["start"]), int(c["len"]))
                break
        if death is None:
            raise SystemExit(f"{name}: no death clip")
        death_starts.append(death[0])
        death_lens.append(death[1])
        if all_edges is None:
            all_edges = lines
        elif lines != all_edges:
            print(f"warning: {name} edges differ from Grunt; using Grunt edges")
        prefix = PREFIX[ti]
        nframes = len(gx) // NVERTS
        if nframes > max_nframes:
            max_nframes = nframes
        parts.append(f"; --- {name} ({nframes} frames) ---")
        for ci, c in enumerate(clips):
            parts.append(f"{clip_const(prefix, c['name'])}\t= {ci}\t; start {c['start']} len {c['len']}")
        parts.append(f"{prefix}_nclips\t= {len(clips)}")
        parts.append(f"{prefix}_nframes\t= {nframes}")
        parts.append(f"{prefix}_clip_start")
        parts.append("\t!byte " + ",".join(str(int(c["start"])) for c in clips))
        parts.append(f"{prefix}_clip_len")
        parts.append("\t!byte " + ",".join(str(int(c["len"])) for c in clips))
        parts.append(f"{prefix}_gx")
        parts.append(bchunk(gx).rstrip())
        parts.append(f"{prefix}_gy")
        parts.append(bchunk(gy).rstrip())
        parts.append(f"{prefix}_gz")
        parts.append(bchunk(gz).rstrip())
        parts.append("")

    edge_bytes: list[int] = []
    assert all_edges is not None
    for a, b in all_edges:
        edge_bytes.append(int(a))
        edge_bytes.append(int(b))
    parts.append("enemy_edges")
    parts.append("\t!byte " + ",".join(str(b) for b in edge_bytes))
    parts.append("enemy_edge_vert")
    parts.append("\t!byte " + ",".join("0" for _ in all_edges))
    parts.append("")
    parts.append("enemy_gx_lo\t!byte <grunt_gx, <rott_gx")
    parts.append("enemy_gx_hi\t!byte >grunt_gx, >rott_gx")
    parts.append("enemy_gy_lo\t!byte <grunt_gy, <rott_gy")
    parts.append("enemy_gy_hi\t!byte >grunt_gy, >rott_gy")
    parts.append("enemy_gz_lo\t!byte <grunt_gz, <rott_gz")
    parts.append("enemy_gz_hi\t!byte >grunt_gz, >rott_gz")
    parts.append("; Role clips — hand-tuned; keep in sync with enemy.asm AI")
    parts.append("enemy_stand_start\t!byte 0, 44")
    parts.append("enemy_stand_len\t\t!byte 8, 9")
    parts.append("enemy_alert_start\t!byte 18, 44")
    parts.append("enemy_alert_len\t\t!byte 11, 2")
    parts.append("enemy_run_start\t\t!byte 35, 23")
    parts.append("enemy_run_len\t\t!byte 8, 12")
    parts.append("enemy_attack_start\t!byte 43, 0")
    parts.append("enemy_attack_len\t!byte 9, 8")
    parts.append("enemy_pain_start\t\t!byte 29, 17")
    parts.append("enemy_pain_len\t\t!byte 6, 6")
    parts.append(
        "enemy_death_start\t!byte "
        + ", ".join(str(s) for s in death_starts)
    )
    parts.append(
        "enemy_death_len\t\t!byte "
        + ", ".join(str(n) for n in death_lens)
    )
    parts.append("enemy_range\t\t!byte 30, 4\t\t; approach stop (Chebyshev XZ)")
    parts.append("enemy_hp_init\t\t!byte 2, 2")
    parts.append("enemy_pain_chance\t!byte $80, $c0\t\t; rnd8 < chance → pain")
    # BP_SHELLS=0; $FF = no drop. Index = ent_type.
    parts.append("enemy_drop_type\t!byte 0, $ff\t\t; Grunt shells, Rott none")
    parts.append("")
    # Absolute frame → byte offset into *_gx/gy/gz (frame * NVERTS)
    parts.append(f"; frame * {NVERTS} as 16-bit offset (0..{max_nframes - 1})")
    parts.append("frame13_lo")
    parts.append(
        "\t!byte " + ",".join(f"${((i * NVERTS) & 0xFF):02x}" for i in range(max_nframes))
    )
    parts.append("frame13_hi")
    parts.append(
        "\t!byte " + ",".join(f"${((i * NVERTS) >> 8):02x}" for i in range(max_nframes))
    )
    parts.append("")

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUT.relative_to(ROOT)} "
        f"(walk start={walk_starts} len={walk_lens} "
        f"death start={death_starts} len={death_lens})"
    )


if __name__ == "__main__":
    main()
