#!/usr/bin/env python3
"""Export Grunt + Rottweiler poses + clips → src/enemy_data.asm."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "editor" / "quake64.json"
OUT = ROOT / "src" / "enemy_data.asm"

NVERTS = 13
TYPES = ["Grunt", "Rottweiler"]
PREFIX = ["grunt", "rott"]
PAIN_MAX = 4
PAIN_KEY = re.compile(r"^pain[a-z]?$")
DEATH_KEY = re.compile(r"^(bdeath|death[a-z]?)$")

# Original Quake HP; ROM stores Quake // 5 (byte-sized, Shambler 120 fits).
HP_QUAKE = {
    "Grunt": 30,
    "Rottweiler": 25,
    "Knight": 75,
    "Scrag": 80,
    "Ogre": 200,
    "Shambler": 600,
}

# Role clip names (and optional len override). Pain/death are variant lists.
ROLE_CLIPS = {
    "Grunt": {
        "stand": ("stand", None),
        "alert": ("load", None),
        "run": ("run", None),
        "walk": ("prowl", None),
        "attack": ("shoot", None),
    },
    "Rottweiler": {
        "stand": ("stand", None),
        "alert": ("stand", 2),
        "run": ("run", None),
        "walk": ("walk", None),
        "attack": ("leap", None),
    },
}

# Facing folds into the runtime rotate angle (ent_rotate: a = yaw − rot),
# so no pre-baked 45° tables are needed.


def clip_key(name: str) -> str:
    return str(name).rstrip("_").lower()


def clip_const(prefix: str, name: str) -> str:
    key = clip_key(name).upper()
    key = re.sub(r"[^A-Z0-9]+", "_", key).strip("_")
    return f"{prefix.upper()}_CLIP_{key}"


def find_clip(enemy: dict, *names: str) -> tuple[int, int] | None:
    clips = enemy.get("clips") or []
    for want in names:
        for c in clips:
            if clip_key(c.get("name", "")) == want:
                return int(c["start"]), int(c["len"])
    return None


def find_role(enemy: dict, role: str) -> tuple[int, int]:
    spec = ROLE_CLIPS.get(enemy["name"], {}).get(role)
    if spec is None:
        raise SystemExit(f"{enemy['name']}: no role {role}")
    name, len_override = spec
    found = find_clip(enemy, name)
    if found is None:
        raise SystemExit(f"{enemy['name']}: no {name} clip for role {role}")
    start, length = found
    if len_override is not None:
        length = min(length, int(len_override))
    return start, length


def find_variant_clips(enemy: dict, key_re: re.Pattern, what: str) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for c in enemy.get("clips") or []:
        if key_re.match(clip_key(c.get("name", ""))):
            out.append((int(c["start"]), int(c["len"])))
            if len(out) >= PAIN_MAX:
                break
    if not out:
        raise SystemExit(f"{enemy['name']}: no {what} clip")
    return out


def pad_variants(clips: list[tuple[int, int]]) -> tuple[int, list[int], list[int]]:
    starts: list[int] = []
    lens: list[int] = []
    for i in range(PAIN_MAX):
        if i < len(clips):
            starts.append(clips[i][0])
            lens.append(clips[i][1])
        else:
            starts.append(0)
            lens.append(0)
    return len(clips), starts, lens


def s8(n: int) -> int:
    n = int(n)
    if n < -128 or n > 127:
        raise ValueError(f"vert coord out of signed byte range: {n}")
    return n & 0xFF


def bchunk(data: list[int], w: int = 13) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def export_type(enemy: dict) -> tuple[list[int], list[int], list[int], list[list[int]], list[dict]]:
    lines = enemy["lines"]
    frames = enemy["frames"]
    clips = enemy.get("clips") or []
    if len(lines) != NVERTS:
        raise SystemExit(f"{enemy['name']}: expected {NVERTS} lines, got {len(lines)}")
    if not frames:
        raise SystemExit(f"{enemy['name']}: no frames")
    gx: list[int] = []
    gy: list[int] = []
    gz: list[int] = []
    for fi, fr in enumerate(frames):
        if len(fr) != NVERTS:
            raise SystemExit(f"{enemy['name']} frame {fi}: bad vert count")
        for v in fr:
            gx.append(s8(v["x"]))
            gy.append(s8(v["y"]))
            gz.append(s8(v["z"]))
    return gx, gy, gz, lines, clips


def main() -> None:
    doc = json.loads(DOC.read_text(encoding="utf-8"))
    by_name = {e["name"]: e for e in doc["enemies"]}
    parts = [
        "; Generated by tools/genenemies.py — do not edit",
        "; All clips as signed bytes (runtime (g*trig)>>2 → 8.8)",
        "; Facing folds into ent_rotate (a = yaw − rot) — no 45° bake",
        "ENEMY_NTYPES\t= 2",
        "ENT_GRUNT\t= 0",
        "ENT_ROTT\t= 1",
        "",
    ]
    all_edges = None
    roles: dict[str, list[int]] = {
        "stand_start": [],
        "stand_len": [],
        "alert_start": [],
        "alert_len": [],
        "run_start": [],
        "run_len": [],
        "walk_start": [],
        "walk_len": [],
        "attack_start": [],
        "attack_len": [],
    }
    pain_n: list[int] = []
    pain_start: list[int] = []
    pain_len: list[int] = []
    death_n: list[int] = []
    death_start: list[int] = []
    death_len: list[int] = []
    max_nframes = 0

    for ti, name in enumerate(TYPES):
        if name not in by_name:
            raise SystemExit(f"missing enemy {name}")
        enemy = by_name[name]
        gx, gy, gz, lines, clips = export_type(enemy)
        for role in ("stand", "alert", "run", "walk", "attack"):
            start, length = find_role(enemy, role)
            roles[f"{role}_start"].append(start)
            roles[f"{role}_len"].append(length)
        n, starts, lens = pad_variants(find_variant_clips(enemy, PAIN_KEY, "pain"))
        pain_n.append(n)
        pain_start.extend(starts)
        pain_len.extend(lens)
        n, starts, lens = pad_variants(find_variant_clips(enemy, DEATH_KEY, "death"))
        death_n.append(n)
        death_start.extend(starts)
        death_len.extend(lens)
        if all_edges is None:
            all_edges = lines
        elif lines != all_edges:
            print(f"warning: {name} edges differ from Grunt; using Grunt edges")
        prefix = PREFIX[ti]
        nframes = len(gx) // NVERTS
        if nframes > max_nframes:
            max_nframes = nframes
        parts.append(f"; --- {name} ({nframes} frames) ---")
        for ci, c in enumerate(clips):
            parts.append(f"{clip_const(prefix, c['name'])}\t= {ci}\t; start {c['start']} len {c['len']}")
        parts.append(f"{prefix}_nclips\t= {len(clips)}")
        parts.append(f"{prefix}_nframes\t= {nframes}")
        parts.append(f"{prefix}_clip_start")
        parts.append("\t!byte " + ",".join(str(int(c["start"])) for c in clips))
        parts.append(f"{prefix}_clip_len")
        parts.append("\t!byte " + ",".join(str(int(c["len"])) for c in clips))
        parts.append(f"{prefix}_gx")
        parts.append(bchunk(gx).rstrip())
        parts.append(f"{prefix}_gy")
        parts.append(bchunk(gy).rstrip())
        parts.append(f"{prefix}_gz")
        parts.append(bchunk(gz).rstrip())
        parts.append("")

    edge_bytes: list[int] = []
    assert all_edges is not None
    for a, b in all_edges:
        edge_bytes.append(int(a))
        edge_bytes.append(int(b))
    parts.append("enemy_edges")
    parts.append("\t!byte " + ",".join(str(b) for b in edge_bytes))
    parts.append("enemy_edge_vert")
    parts.append("\t!byte " + ",".join("0" for _ in all_edges))
    parts.append("")
    parts.append("enemy_gx_lo\t!byte <grunt_gx, <rott_gx")
    parts.append("enemy_gx_hi\t!byte >grunt_gx, >rott_gx")
    parts.append("enemy_gy_lo\t!byte <grunt_gy, <rott_gy")
    parts.append("enemy_gy_hi\t!byte >grunt_gy, >rott_gy")
    parts.append("enemy_gz_lo\t!byte <grunt_gz, <rott_gz")
    parts.append("enemy_gz_hi\t!byte >grunt_gz, >rott_gz")
    parts.append("PAIN_MAX\t= 4\t\t; variants per type; pain_var_off uses ASL×2")
    parts.append("; Role clips — looked up by name from editor JSON")
    parts.append("enemy_stand_start\t!byte " + ", ".join(str(n) for n in roles["stand_start"]))
    parts.append("enemy_stand_len\t\t!byte " + ", ".join(str(n) for n in roles["stand_len"]))
    parts.append("enemy_alert_start\t!byte " + ", ".join(str(n) for n in roles["alert_start"]))
    parts.append(
        "enemy_alert_len\t\t!byte "
        + ", ".join(str(n) for n in roles["alert_len"])
        + "\t\t; Rott first 2 of stand"
    )
    parts.append("enemy_run_start\t\t!byte " + ", ".join(str(n) for n in roles["run_start"]))
    parts.append("enemy_run_len\t\t!byte " + ", ".join(str(n) for n in roles["run_len"]))
    parts.append(
        "enemy_walk_start\t\t!byte "
        + ", ".join(str(n) for n in roles["walk_start"])
        + "\t\t; Grunt prowl, Rott walk"
    )
    parts.append("enemy_walk_len\t\t!byte " + ", ".join(str(n) for n in roles["walk_len"]))
    parts.append(
        "enemy_attack_start\t!byte "
        + ", ".join(str(n) for n in roles["attack_start"])
        + "\t\t; Grunt shoot, Rott leap"
    )
    parts.append("enemy_attack_len\t!byte " + ", ".join(str(n) for n in roles["attack_len"]))
    parts.append("enemy_pain_n\t\t!byte " + ", ".join(str(n) for n in pain_n))
    parts.append(
        "enemy_pain_start\t!byte " + ", ".join(str(n) for n in pain_start)
        + "\t; type * PAIN_MAX + variant"
    )
    parts.append("enemy_pain_len\t\t!byte " + ", ".join(str(n) for n in pain_len))
    parts.append("enemy_death_n\t\t!byte " + ", ".join(str(n) for n in death_n))
    parts.append(
        "enemy_death_start\t!byte " + ", ".join(str(n) for n in death_start)
        + "\t; type * PAIN_MAX + variant"
    )
    parts.append("enemy_death_len\t\t!byte " + ", ".join(str(n) for n in death_len))
    parts.append("enemy_range\t\t!byte 30, 4\t\t; approach stop (Chebyshev XZ)")
    hp_bytes = ", ".join(str(HP_QUAKE[t] // 5) for t in TYPES)
    hp_note = ", ".join(f"{t} {HP_QUAKE[t]}→{HP_QUAKE[t] // 5}" for t in TYPES)
    parts.append(f"; Quake HP÷5: {hp_note}")
    parts.append(f"enemy_hp_init\t\t!byte {hp_bytes}")
    parts.append("enemy_pain_chance\t!byte $80, $c0\t\t; rnd8 < chance → pain")
    # BP_SHELLS5=7; $FF = no drop. Index = ent_type.
    parts.append("enemy_drop_type\t!byte 7, $ff\t\t; Grunt 5 shells, Rott none")
    parts.append("enemy_fire_frame\t!byte 2, 4\t\t; grunt muzzle / rott leap hit frame")
    parts.append("")
    # Absolute frame → byte offset into *_gx/gy/gz (frame * NVERTS)
    parts.append(f"; frame * {NVERTS} as 16-bit offset (0..{max_nframes - 1})")
    parts.append("frame13_lo")
    parts.append(
        "\t!byte " + ",".join(f"${((i * NVERTS) & 0xFF):02x}" for i in range(max_nframes))
    )
    parts.append("frame13_hi")
    parts.append(
        "\t!byte " + ",".join(f"${((i * NVERTS) >> 8):02x}" for i in range(max_nframes))
    )
    parts.append("")

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUT.relative_to(ROOT)} "
        f"(walk start={roles['walk_start']} len={roles['walk_len']} "
        f"pain n={pain_n} death n={death_n})"
    )


if __name__ == "__main__":
    main()
