#!/usr/bin/env python3
"""Export Grunt walk frames (signed bytes) + edges from editor JSON → grunt_data.asm."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "editor" / "quake64.json"
OUT = ROOT / "src" / "grunt_data.asm"

WALK_LEN = 4
LEGACY_WALK_START = 4
NVERTS = 13


def s8(n: int) -> int:
    n = int(n)
    if n < -128 or n > 127:
        raise ValueError(f"vert coord out of signed byte range: {n}")
    return n & 0xFF


def bchunk(data: list[int], w: int = 13) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def walk_frame_indices(enemy: dict) -> list[int]:
    clips = enemy.get("clips") or []
    if clips:
        for name in ("prowl", "walk", "fly"):
            for c in clips:
                if c.get("name") == name:
                    start = int(c["start"])
                    ln = min(WALK_LEN, int(c["len"]))
                    return list(range(start, start + ln))
    frames = enemy.get("frames") or []
    if len(frames) >= LEGACY_WALK_START + WALK_LEN:
        return list(range(LEGACY_WALK_START, LEGACY_WALK_START + WALK_LEN))
    raise SystemExit("Grunt: no prowl/walk/fly clip and frames too short for legacy export")


def main() -> None:
    doc = json.loads(DOC.read_text(encoding="utf-8"))
    grunt = next(e for e in doc["enemies"] if e["name"] == "Grunt")
    lines = grunt["lines"]
    frames = grunt["frames"]
    if len(lines) != NVERTS:
        raise SystemExit(f"expected {NVERTS} lines, got {len(lines)}")
    walk_frames = walk_frame_indices(grunt)
    if len(walk_frames) < WALK_LEN:
        raise SystemExit("Grunt walk clip shorter than 4 frames")

    gx: list[int] = []
    gy: list[int] = []
    gz: list[int] = []
    for fi in walk_frames[:WALK_LEN]:
        fr = frames[fi]
        if len(fr) != NVERTS:
            raise SystemExit(f"frame {fi}: expected {NVERTS} verts, got {len(fr)}")
        for v in fr:
            gx.append(s8(v["x"]))
            gy.append(s8(v["y"]))
            gz.append(s8(v["z"]))

    edge_bytes: list[int] = []
    for a, b in lines:
        edge_bytes.append(int(a))
        edge_bytes.append(int(b))

    parts = [
        "; Generated by tools/gengrunt.py — do not edit",
        "; Grunt walk 0..3 as signed bytes (runtime <<5 → 8.8)",
        "gx",
        bchunk(gx).rstrip(),
        "gy",
        bchunk(gy).rstrip(),
        "gz",
        bchunk(gz).rstrip(),
        "edges",
        "\t!byte " + ",".join(str(b) for b in edge_bytes),
        "",
    ]
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(gx)} verts × 3 axes, {len(lines)} edges)")


if __name__ == "__main__":
    main()
