"""Emit unrolled Mike 30k loop bodies into src/_line_bodies.asm"""
from pathlib import Path

BITS = [0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01]
OUT = Path(__file__).resolve().parents[1] / "src" / "_line_bodies.asm"


def sd(i: int, b: int) -> str:
    n = f"sd{i}"
    return f"""{n}
	lda (colptr),y
	ora #${b:02x}
	sta (colptr),y
	dex
	bne {n}c
	rts
{n}c
	lda err_l
	sbc dy
	bcs {n}ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc {n}d
	jsr y_cross_down
	jmp {n}d
{n}ny
	sta err_l
{n}d
	sec
"""


def su(i: int, b: int) -> str:
    n = f"su{i}"
    return f"""{n}
	lda (colptr),y
	ora #${b:02x}
	sta (colptr),y
	dex
	bne {n}c
	rts
{n}c
	lda err_l
	sbc dy
	bcs {n}ny
	adc dx
	sta err_l
	dey
	bpl {n}d
	jsr y_cross_up
	jmp {n}d
{n}ny
	sta err_l
{n}d
	sec
"""


def td(i: int, b: int) -> str:
    n = f"td{i}"
    nxt = f"td{i + 1}" if i < 7 else "td0"
    step = (
        f"\tjmp {nxt}\n"
        if i < 7
        else """\tclc
	lda colptr
	adc #64
	sta colptr
	bcc td7nc
	inc colptr+1
td7nc
	sec
	jmp td0
"""
    )
    return f"""{n}
	lda (colptr),y
	ora #${b:02x}
	sta (colptr),y
	dex
	bne {n}c
	rts
{n}c
	iny
	cpy #64
	bcc {n}e
	jsr y_cross_down
{n}e
	sec
	lda err_l
	sbc dx
	bcs {n}s
	adc dy
	sta err_l
{step}{n}s
	sta err_l
	jmp {n}
"""


def tu(i: int, b: int) -> str:
    n = f"tu{i}"
    nxt = f"tu{i + 1}" if i < 7 else "tu0"
    step = (
        f"\tjmp {nxt}\n"
        if i < 7
        else """\tclc
	lda colptr
	adc #64
	sta colptr
	bcc tu7nc
	inc colptr+1
tu7nc
	sec
	jmp tu0
"""
    )
    return f"""{n}
	lda (colptr),y
	ora #${b:02x}
	sta (colptr),y
	dex
	bne {n}c
	rts
{n}c
	dey
	bpl {n}e
	jsr y_cross_up
{n}e
	sec
	lda err_l
	sbc dx
	bcs {n}s
	adc dy
	sta err_l
{step}{n}s
	sta err_l
	jmp {n}
"""


def main() -> None:
    parts = [
        "; Auto-generated by tools/genlinebodies.py — unrolled Mike 30k bodies\n",
        "; ---- X major +Y ----\n",
        "sdn_l\t!byte <sd0,<sd1,<sd2,<sd3,<sd4,<sd5,<sd6,<sd7\n",
        "sdn_h\t!byte >sd0,>sd1,>sd2,>sd3,>sd4,>sd5,>sd6,>sd7\n",
    ]
    parts.extend(sd(i, b) for i, b in enumerate(BITS))
    parts.append(
        """	clc
	lda colptr
	adc #64
	sta colptr
	bcc sdcol
	inc colptr+1
sdcol
	sec
	jmp sd0

; ---- X major -Y ----
sup_l	!byte <su0,<su1,<su2,<su3,<su4,<su5,<su6,<su7
sup_h	!byte >su0,>su1,>su2,>su3,>su4,>su5,>su6,>su7
"""
    )
    parts.extend(su(i, b) for i, b in enumerate(BITS))
    parts.append(
        """	clc
	lda colptr
	adc #64
	sta colptr
	bcc sucol
	inc colptr+1
sucol
	sec
	jmp su0

; ---- Y major +Y ----
std_l	!byte <td0,<td1,<td2,<td3,<td4,<td5,<td6,<td7
std_h	!byte >td0,>td1,>td2,>td3,>td4,>td5,>td6,>td7
"""
    )
    parts.extend(td(i, b) for i, b in enumerate(BITS))
    parts.append(
        """; ---- Y major -Y ----
stu_l	!byte <tu0,<tu1,<tu2,<tu3,<tu4,<tu5,<tu6,<tu7
stu_h	!byte >tu0,>tu1,>tu2,>tu3,>tu4,>tu5,>tu6,>tu7
"""
    )
    parts.extend(tu(i, b) for i, b in enumerate(BITS))
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
