#!/usr/bin/env python3
"""Export GAME entry points the $C000 quicksave overlay calls."""

from __future__ import annotations

import argparse
from pathlib import Path

from mkreloc import parse_labels

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "qsyms.asm"

REQUIRED = [
    "LoadPrg",
    "LoadLevel",
    "maybe_stream_room",
    "SavePrg",
    "save_bind",
    "load_view_trig",
    "mulset_init",
    "game_zp_init",
    "init_hud",
    "hud_ammo",
    "hud_powerup",
    "setup_weapon",
    "init_irq",
]
KRILL_SKIP = {"SavePrg", "save_bind"}


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate quicksave overlay GAME symbols")
    ap.add_argument("--labels", default="game.lbl")
    ap.add_argument("--krill", action="store_true", help="omit KERNAL SavePrg symbols")
    args = ap.parse_args()
    path = Path(args.labels)
    if not path.is_file():
        path = ROOT / path
    want = [name for name in REQUIRED if not (args.krill and name in KRILL_SKIP)]
    labels = parse_labels(path)
    missing = [name for name in want if name not in labels]
    if missing:
        raise SystemExit(f"{path}: missing quicksave symbols: {', '.join(missing)}")
    lines = ["; Generated by tools/genqsyms.py — GAME entries for the $C000 saver"]
    lines.extend(f"{name}\t= ${labels[name]:04x}" for name in want)
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(want)} symbols)")


if __name__ == "__main__":
    main()
