"""Emit inlined log-add rotate body (no jsr logadd7 / signed_log in the vertex loop)."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "_rotate_body.asm"


def slog(n: str, lda: str, logd: str, sgd: str, keep: str = "") -> str:
    keep_l = f"\t{keep}\n" if keep else ""
    return f"""	{lda}
{keep_l}	ldy #0
	cmp #0
	bpl {n}p
	ldy #$80
	eor #$ff
	clc
	adc #1
{n}p
	tax
	lda LOGTAB,x
	sta {logd}
	sty {sgd}
"""


def prod(n: str, loga: str, logb: str, siga: str, sigb: str) -> str:
    return f"""	lda {siga}
	eor {sigb}
	sta mul_sign
	lda {loga}
	clc
	adc {logb}
	bcc {n}noc
	cmp #224
	bcc {n}chi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp {n}got
{n}chi
	adc #32
	tax
	lda ALOGTAB,x
	jmp {n}got
{n}noc
	cmp #224
	bcc {n}z
	sbc #224
	tax
	lda ALOGTAB,x
{n}got
	cmp #128
	bcc {n}sg
	lda #$7f
{n}sg
	bit mul_sign
	bpl {n}out
	eor #$ff
	clc
	adc #1
	jmp {n}out
{n}z
	lda #0
{n}out
"""


def main() -> None:
    parts = [
        "; Auto-generated by tools/genrotate.py — inlined log|v|+log|trig| products\n",
        "	ldy yaw\n",
        slog("tcs", "lda COSTAB,y", "log_cs", "sg_cs"),
        "	ldy yaw\n",
        slog("tsn", "lda SINTAB,y", "log_sn", "sg_sn"),
        "	ldy pitch\n",
        slog("tcp", "lda COSTAB,y", "log_cp", "sg_cp"),
        "	ldy pitch\n",
        slog("tsp", "lda SINTAB,y", "log_sp", "sg_sp"),
        """	; Camera look: rotate (x, z+CAMZ), not the cube about its centre.
	lda #CAMZ
	tax
	lda LOGTAB,x
	sta log_x
	lda #0
	sta sg_x
""",
        prod("czs", "log_x", "log_sn", "sg_x", "sg_sn"),
        "	sta look_sx\n",
        prod("czc", "log_x", "log_cs", "sg_x", "sg_cs"),
        "	sta look_sz\n",
        slog("lsz", "lda look_sz", "log_rz", "sg_rz"),
        prod("lss", "log_rz", "log_sp", "sg_rz", "sg_sp"),
        "	sta look_sy\n",
        prod("lsc", "log_rz", "log_cp", "sg_rz", "sg_cp"),
        """	sta z_bias
	lda #0
	sta vindex
.rvert
	ldx vindex
""",
        slog("vx", "lda vx,x\n\tsec\n\tsbc cam_x", "log_x", "sg_x"),
        "	ldx vindex\n",
        slog("vz", "lda vz,x\n\tsec\n\tsbc cam_z", "log_z", "sg_z"),
        "	ldx vindex\n",
        slog("vy", "lda vy,x\n\tsec\n\tsbc cam_y", "log_y", "sg_y", keep="sta ry"),
        "	; rx = x*cs - z*sn\n",
        prod("xc", "log_x", "log_cs", "sg_x", "sg_cs"),
        "	sta rx\n",
        prod("zs", "log_z", "log_sn", "sg_z", "sg_sn"),
        """	sta rot0
	lda rx
	sec
	sbc rot0
	sec
	sbc look_sx
	sta rx
	; rz = x*sn + z*cs
""",
        prod("xs", "log_x", "log_sn", "sg_x", "sg_sn"),
        "	sta rz\n",
        prod("zc", "log_z", "log_cs", "sg_z", "sg_cs"),
        """	clc
	adc rz
	sta rz
""",
        slog("rz", "lda rz", "log_rz", "sg_rz"),
        "	; y' = y*cp - rz*sp\n",
        prod("yc", "log_y", "log_cp", "sg_y", "sg_cp"),
        "	sta rot2\n",
        prod("rs", "log_rz", "log_sp", "sg_rz", "sg_sp"),
        """	sta rot1
	lda rot2
	sec
	sbc rot1
	sec
	sbc look_sy
	sta rot2
	; z'' = y*sp + rz*cp
""",
        prod("ys", "log_y", "log_sp", "sg_y", "sg_sp"),
        "	sta rot0\n",
        prod("rc", "log_rz", "log_cp", "sg_rz", "sg_cp"),
        """	clc
	adc rot0
	sta rz
	lda rot2
	sta ry
	ldx vindex
	lda rx
	sta CAM_X,x
	lda ry
	sta CAM_Y,x
	lda rz
	sta CAM_Z,x
	inc vindex
	lda vindex
	cmp #8
	beq +
	jmp .rvert
+
	rts
""",
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
