"""Emit per-frame yaw trig byte loads (vertex rotate is in cube.asm)."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "_rotate_body.asm"


def main() -> None:
    OUT.write_text(
        """; Auto-generated by tools/genrotate.py — load sin/cos for yaw-only view
; and prime the fast-multiply pointer sets (A=cos, B=sin)
	ldy yaw
	lda COSTAB,y
	sta cs_b
	jsr mulset_a
	lda SINTAB,y
	sta sn_b
	jsr mulset_b
""",
        encoding="utf-8",
    )
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
