"""Emit per-frame yaw/pitch trig byte loads (vertex rotate is in cube.asm)."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "_rotate_body.asm"


def main() -> None:
    OUT.write_text(
        """; Auto-generated by tools/genrotate.py — load sin/cos for 16-bit view rotate
	ldy yaw
	lda COSTAB,y
	sta cs_b
	lda SINTAB,y
	sta sn_b
	ldy pitch
	lda COSTAB,y
	sta cp_b
	lda SINTAB,y
	sta sp_b
""",
        encoding="utf-8",
    )
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
