#!/usr/bin/env python3
"""Pack assets/weapons/splat_0..2.png → src/splat_spr.asm."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PNG_DIR = ROOT / "assets" / "weapons"
OUT = ROOT / "src" / "splat_spr.asm"

FW = 24
FH = 21
N = 3


def bchunk(data: list[int], width: int = 16) -> str:
    lines = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def pack_24x21(pix: list[list[int]]) -> list[int]:
    out = [0] * 64
    for y in range(FH):
        for col in range(3):
            b = 0
            for bit in range(8):
                if pix[y][col * 8 + bit]:
                    b |= 0x80 >> bit
            out[y * 3 + col] = b
    return out


def load_png(path: Path) -> list[list[int]]:
    try:
        from PIL import Image
    except ImportError as e:
        raise SystemExit("Pillow is required: pip install Pillow") from e
    im = Image.open(path).convert("RGB")
    if im.size != (FW, FH):
        raise SystemExit(f"{path.name}: expected {FW}x{FH}, got {im.size[0]}x{im.size[1]}")
    pix = [[0] * FW for _ in range(FH)]
    src = im.load()
    for y in range(FH):
        for x in range(FW):
            r, g, b = src[x, y][:3]
            if r > 16 or g > 16 or b > 16:
                pix[y][x] = 1
    return pix


def main() -> None:
    parts = [
        "; Auto-generated by tools/gensplat.py — do not edit\n",
        "; Distance LOD: 0 = near/large … 2 = far/small (24×21 hi-res)\n",
        "; Source: assets/weapons/splat_0..2.png (ink centered for tip−12/−10)\n",
    ]
    for i in range(N):
        path = PNG_DIR / f"splat_{i}.png"
        if not path.is_file():
            raise SystemExit(f"missing {path.relative_to(ROOT)}")
        data = pack_24x21(load_png(path))
        parts.append(f"spr_splat_{i}\n")
        parts.append(bchunk(data))
        parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({N}×64 bytes)")


if __name__ == "__main__":
    main()
