#!/usr/bin/env python3
"""Pack assets/weapons/splat_0..2.png → src/splat_spr.asm (zeromask)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from sprmask import (  # noqa: E402
    CELL,
    bchunk,
    load_fx_raw,
    pack_zeromask,
)

PNG_DIR = ROOT / "assets" / "weapons"
OUT = ROOT / "src" / "splat_spr.asm"
N = 3


def main() -> None:
    parts = [
        "; Auto-generated by tools/gensplat.py — do not edit\n",
        "; zeromask: 8 occupancy bytes + nonzero payload (24×21 hi-res)\n",
        "; Distance LOD: 0 = near/large … 2 = far/small\n",
        "; Source: assets/weapons/splat_0..2.png (ink centered for tip−12/−10)\n",
    ]
    sizes = []
    for i in range(N):
        raw = load_fx_raw(PNG_DIR / f"splat_{i}.png", OUT, f"spr_splat_{i}")
        packed = pack_zeromask(raw)
        sizes.append(len(packed))
        parts.append(f"spr_splat_{i}\n")
        parts.append(bchunk(packed))
        parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} packed {sizes} (was {N}×{CELL})")


if __name__ == "__main__":
    main()
