#!/usr/bin/env python3
"""Both screen matrices (HUD spaces, viewport unique codes, MARGIN_CH bars)."""

from __future__ import annotations

from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src"
OUT = SRC / "screens.asm"

SCR_A = 0xC000
VIEW_COL = 8
VIEW_ROW = 9
VIEW_W = 24
VIEW_H = 16
MARGIN_CH = 192
HUD_CH_SP = 0x20
ROWS = 25
COLS = 40
MATRIX = 1024  # 1000 cells + 24-byte pad / sprite pointer slack


def bchunk(data: list[int], w: int = 16) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def matrix() -> list[int]:
    out = [0] * MATRIX
    for row in range(ROWS):
        for col in range(COLS):
            i = row * COLS + col
            if row < VIEW_ROW:
                out[i] = HUD_CH_SP
            elif row < VIEW_ROW + VIEW_H:
                if col < VIEW_COL or col >= VIEW_COL + VIEW_W:
                    out[i] = MARGIN_CH
                else:
                    vcol = col - VIEW_COL
                    vrow = row - VIEW_ROW
                    out[i] = vcol * 8 + (vrow & 7)
    return out


def main() -> None:
    a = matrix()
    b = matrix()
    body = a + b
    parts = [
        "!cpu 6502\n",
        '!to "scr.prg", cbm\n',
        "; Auto-generated by tools/genscreens.py — do not edit\n",
        "; $C000 matrix A, $C400 matrix B. HUD $20, viewport unique, margins 192.\n",
        f"*= ${SCR_A:04X}\n",
        "scr_a\n",
        bchunk(a),
        "scr_b\n",
        bchunk(b),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
