#!/usr/bin/env python3
"""Log / antilog / sin / invz staging (tables.asm) and Judd quarter-square (sqtab.asm).

ACME assembles these listings to tab.prg ($8000) and sqt.prg ($F000).
Runtime COSTAB = SINTAB+64 (320-byte sin); copy_tab unpacks charset tails.
"""

from __future__ import annotations

import math
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src"
OUT = SRC / "tables.asm"
SQOUT = SRC / "sqtab.asm"


def bchunk(data: list[int], w: int = 16) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def main() -> None:
    logtab = [0]
    for i in range(1, 256):
        logtab.append(max(0, min(255, int(round(32.0 * math.log2(i))))))

    alog = []
    for i in range(512):
        alog.append(min(255, int(round(2 ** (i / 32.0)))))

    # 320 bytes: sin[0..255] plus first quadrant again so COSTAB = SINTAB+64.
    sintab = []
    for i in range(320):
        v = int(round(127.0 * math.sin(i * 2.0 * math.pi / 256.0)))
        v = max(-127, min(127, v))
        sintab.append(v & 255)

    FOCAL = 100
    inv = [(FOCAL << 16) // d for d in range(128, 256)]
    invzl = [v & 255 for v in inv]
    invzh = [(v >> 8) & 255 for v in inv]

    ntab = len(alog) + len(logtab) + len(sintab) + len(invzl) + len(invzh)
    parts = [
        "!cpu 6502\n",
        '!to "tab.prg", cbm\n',
        "; Auto-generated by tools/gentables.py — do not edit\n",
        "; Staging @ $8000 for copy_tab. Runtime: COSTAB = SINTAB+64.\n",
        "; Order: alog 512, log 256, sin 320, invzl 128, invzh 128\n",
        "*= $8000\n",
        "tab_alog\n",
        bchunk(alog),
        "tab_log\n",
        bchunk(logtab),
        "tab_sin\n",
        bchunk(sintab),
        "tab_invzl\n",
        bchunk(invzl),
        "tab_invzh\n",
        bchunk(invzh),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({ntab} bytes)")

    sq = [(i * i) // 4 for i in range(512)]
    sqlo = [v & 255 for v in sq]
    sqhi = [v >> 8 for v in sq]

    negsq = [((i - 255) * (i - 255)) // 4 for i in range(512)]
    negsqlo = [v & 255 for v in negsq]
    negsqhi = [v >> 8 for v in negsq]

    SQOUT.write_text(
        "!cpu 6502\n"
        '!to "sqt.prg", cbm\n'
        "; Auto-generated by tools/gentables.py — Judd quarter-square (i*i)/4\n"
        "; Load/runtime $F000 — must match sqlo in mem.asm. invz lives in tables.asm.\n"
        "*= $F000\n"
        "sqlo\n"
        + bchunk(sqlo)
        + "sqhi\n"
        + bchunk(sqhi)
        + "; ((i-255)^2)/4 for the pointer multiply\n"
        + "negsqlo\n"
        + bchunk(negsqlo)
        + "negsqhi\n"
        + bchunk(negsqhi),
        encoding="utf-8",
    )
    print(f"Wrote {SQOUT} (2048 bytes)")


if __name__ == "__main__":
    main()
