#!/usr/bin/env python3
"""Log / antilog / sin / cos LUTs for 8-bit projection (architecture $F800)."""

from __future__ import annotations

import math
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "tables.asm"


def bchunk(data: list[int], w: int = 16) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def main() -> None:
    logtab = [0]
    for i in range(1, 256):
        logtab.append(max(0, min(255, int(round(32.0 * math.log2(i))))))

    alog = []
    for i in range(512):
        alog.append(min(255, int(round(2 ** (i / 32.0)))))

    sintab = []
    for i in range(256):
        v = int(round(127.0 * math.sin(i * 2.0 * math.pi / 256.0)))
        v = max(-127, min(127, v))
        sintab.append(v & 255)

    costab = []
    for i in range(256):
        v = int(round(127.0 * math.cos(i * 2.0 * math.pi / 256.0)))
        v = max(-127, min(127, v))
        costab.append(v & 255)

    parts = [
        "; Auto-generated by tools/gentables.py — do not edit\n",
        "; Order: log 256, alog 512, sin 256, cos 256  (runtime $F800)\n",
        bchunk(logtab),
        bchunk(alog),
        bchunk(sintab),
        bchunk(costab),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(logtab) + len(alog) + len(sintab) + len(costab)} bytes)")


if __name__ == "__main__":
    main()
