#!/usr/bin/env python3
"""Pack ui/quakefont.png into a 2K C64 charset (ASCII-indexed 8×8 UDGs)."""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PNG = ROOT / "ui" / "quakefont.png"
OUT = ROOT / "src" / "uifont.asm"

COLS = 5
ROWS = 20
CELL = 8
# Sheet is row-major; first cell is ASCII 31 (blank), space is 32, '0' is 48.
ASCII_BASE = 31


def bchunk(data: list[int], w: int = 16) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def glyph_bytes(im: Image.Image, col: int, row: int) -> list[int]:
    out = []
    for y in range(CELL):
        b = 0
        for x in range(CELL):
            if im.getpixel((col * CELL + x, row * CELL + y)) > 128:
                b |= 0x80 >> x
        out.append(b)
    return out


def main() -> None:
    im = Image.open(PNG).convert("L")
    w, h = im.size
    if w != COLS * CELL or h != ROWS * CELL:
        raise SystemExit(f"{PNG} is {w}x{h}, expected {COLS * CELL}x{ROWS * CELL}")

    charset = [0] * 2048
    for i in range(COLS * ROWS):
        row, col = i // COLS, i % COLS
        code = ASCII_BASE + i
        if code > 255:
            raise SystemExit(f"glyph {i} maps to char {code}")
        off = code * CELL
        charset[off : off + CELL] = glyph_bytes(im, col, row)

    parts = [
        "; Auto-generated by tools/genuifont.py — do not edit\n",
        f"; {PNG.name}: {COLS}x{ROWS} of {CELL}x{CELL}, placed at ASCII {ASCII_BASE}..\n",
        bchunk(charset),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(charset)} bytes)")


if __name__ == "__main__":
    main()
