#!/usr/bin/env python3
"""Pack ui/quakefont.png into a 2K C64 charset (ASCII-indexed 8×8 UDGs)."""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PNG = ROOT / "ui" / "quakefont.png"
POWERUPS = ROOT / "ui" / "powerups.png"
OUT = ROOT / "src" / "uifont.asm"

COLS = 5
ROWS = 20
CELL = 8
# Sheet is row-major; first cell is ASCII 31 (blank), space is 32, '0' is 48.
ASCII_BASE = 31
# Three 16×16 icons → 2×2 tiles each at charset $80+.
PU_CH_BASE = 0x80
PU_ICON = 16
PU_COUNT = 3


def bchunk(data: list[int], w: int = 16) -> str:
    lines = []
    for i in range(0, len(data), w):
        chunk = data[i : i + w]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n"


def glyph_bytes(im: Image.Image, col: int, row: int) -> list[int]:
    out = []
    for y in range(CELL):
        b = 0
        for x in range(CELL):
            if im.getpixel((col * CELL + x, row * CELL + y)) > 128:
                b |= 0x80 >> x
        out.append(b)
    return out


def main() -> None:
    im = Image.open(PNG).convert("L")
    w, h = im.size
    if w != COLS * CELL or h != ROWS * CELL:
        raise SystemExit(f"{PNG} is {w}x{h}, expected {COLS * CELL}x{ROWS * CELL}")

    charset = [0] * 2048
    for i in range(COLS * ROWS):
        row, col = i // COLS, i % COLS
        code = ASCII_BASE + i
        if code > 255:
            raise SystemExit(f"glyph {i} maps to char {code}")
        off = code * CELL
        charset[off : off + CELL] = glyph_bytes(im, col, row)

    if POWERUPS.exists():
        pu = Image.open(POWERUPS).convert("L")
        pw, ph = pu.size
        if pw != PU_COUNT * PU_ICON or ph != PU_ICON:
            raise SystemExit(f"{POWERUPS} is {pw}x{ph}, expected {PU_COUNT * PU_ICON}x{PU_ICON}")
        for icon in range(PU_COUNT):
            for ty in range(2):
                for tx in range(2):
                    code = PU_CH_BASE + icon * 4 + ty * 2 + tx
                    out = []
                    for y in range(CELL):
                        b = 0
                        for x in range(CELL):
                            px = icon * PU_ICON + tx * CELL + x
                            py = ty * CELL + y
                            if pu.getpixel((px, py)) < 128:
                                b |= 0x80 >> x
                        out.append(b)
                    off = code * CELL
                    charset[off : off + CELL] = out

    parts = [
        "; Auto-generated by tools/genuifont.py — do not edit\n",
        f"; {PNG.name}: {COLS}x{ROWS} of {CELL}x{CELL}, placed at ASCII {ASCII_BASE}..\n",
        f"; {POWERUPS.name}: 3x 16x16 → charset ${PU_CH_BASE:02x} (2x2 each, dark=ink)\n",
        bchunk(charset),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(charset)} bytes)")


if __name__ == "__main__":
    main()
