#!/usr/bin/env python3
"""Scan game.prg for SMC map-accessor sites; prefix each map with overlay+reloc.

Macros in src/mapacc.asm emit abs,x / abs,y with operand hi = MAP_SMC_HI
and lo = field id. This must run after ACME writes game.prg and overlay.bin
(see build.bat). Reloc records are dest words only; the patcher reads field
id from the operand lo already in GAME.
"""

from __future__ import annotations

import argparse
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MEM_ASM = ROOT / "src" / "mem.asm"
OVERLAY_BIN = ROOT / "src" / "overlay.bin"
OVERLAY_LBL = ROOT / "overlay.lbl"
PREFIX_ASM = ROOT / "src" / "level_prefix.asm"
MAP_DIR = ROOT / "maps"

ABS_X = {0xBD, 0x9D, 0xDD, 0x7D, 0xFD, 0x1D, 0x3D, 0x5D, 0xBC}
ABS_Y = {0xB9, 0x99, 0xD9, 0x79, 0xF9, 0x19, 0x39, 0x59, 0xBE}
ABS_OPS = ABS_X | ABS_Y

LEVEL_NAMES = [f"e1m{i}" for i in range(1, 9)]
HDR_LEN = 4  # overlay_len word + reloc_len word


def parse_mem_const(name: str) -> int:
    text = MEM_ASM.read_text(encoding="utf-8")
    m = re.search(rf"^{re.escape(name)}\s*=\s*\$([0-9a-fA-F]+)\b", text, re.M)
    if m:
        return int(m.group(1), 16)
    m = re.search(rf"^{re.escape(name)}\s*=\s*([0-9]+)\b", text, re.M)
    if m:
        return int(m.group(1), 10)
    raise SystemExit(f"{MEM_ASM}: missing {name}")


def parse_labels(lbl: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    if not lbl.is_file():
        return out
    for line in lbl.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"al C:([0-9a-fA-F]+) \.(.+)$", line.strip())
        if m:
            out[m.group(2)] = int(m.group(1), 16) & 0xFFFF
    return out


def scan(body: bytes, load: int, sentinel: int, max_id: int) -> list[tuple[int, int]]:
    recs: list[tuple[int, int]] = []
    i = 0
    n = len(body)
    while i + 2 < n:
        op, lo, hi = body[i], body[i + 1], body[i + 2]
        if op in ABS_OPS and hi == sentinel and lo <= max_id:
            recs.append((load + i + 1, lo))
            i += 3
            continue
        i += 1
    return recs


def packed_from_level_prg(raw: bytes, overlay_len: int) -> bytes | None:
    """Return packed map bytes, stripping a previous prefix if present."""
    if len(raw) < 2:
        return None
    payload = raw[2:]
    if len(payload) >= HDR_LEN:
        ov, rel = struct.unpack_from("<HH", payload, 0)
        body = HDR_LEN + ov + rel
        if ov == overlay_len and body <= len(payload):
            return payload[body:]
    return payload


def write_prefix_asm(overlay: bytes, reloc: bytes, bind_tab: int) -> int:
    ov, rel = len(overlay), len(reloc)
    level_prefix = HDR_LEN + ov + rel
    bind_tab_off = HDR_LEN + bind_tab
    reloc_off = HDR_LEN + ov
    PREFIX_ASM.write_text(
        "; Generated by tools/mkreloc.py — prefix on each E1Mn "
        "(header + overlay + reloc)\n"
        f"LEVEL_PREFIX\t= {level_prefix}\n"
        f"BIND_TAB_OFF\t= {bind_tab_off}\n"
        f"RELOC_OFF\t= {reloc_off}\n"
        f"OVERLAY_OFF\t= {HDR_LEN}\n",
        encoding="utf-8",
    )
    return level_prefix


def pack_maps(overlay: bytes, reloc: bytes) -> None:
    header = struct.pack("<HH", len(overlay), len(reloc))
    prefix_body = overlay + reloc
    n = 0
    for name in LEVEL_NAMES:
        prg = MAP_DIR / f"{name}.prg"
        if not prg.is_file() or prg.stat().st_size <= 2:
            continue
        packed = packed_from_level_prg(prg.read_bytes(), len(overlay))
        if packed is None or not packed:
            continue
        prg.write_bytes(struct.pack("<H", 0) + header + prefix_body + packed)
        n += 1
    if n == 0:
        print("mkreloc: no map PRGs to prefix", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build map prefix (overlay + reloc dest words) from game.prg"
    )
    ap.add_argument("game", nargs="?", default="game.prg")
    ap.add_argument("--labels", default="game.lbl")
    ap.add_argument("--overlay", default=str(OVERLAY_BIN))
    args = ap.parse_args()

    sentinel = parse_mem_const("MAP_SMC_HI")

    ov_path = Path(args.overlay)
    if not ov_path.is_file():
        print(f"missing: {ov_path}", file=sys.stderr)
        sys.exit(1)
    overlay = ov_path.read_bytes()
    if not overlay:
        print(f"{ov_path}: empty", file=sys.stderr)
        sys.exit(1)

    ov_lbl = parse_labels(OVERLAY_LBL)
    if "bind_tab" not in ov_lbl:
        print(f"{OVERLAY_LBL}: no bind_tab", file=sys.stderr)
        sys.exit(1)
    bind_tab = ov_lbl["bind_tab"]
    if bind_tab >= len(overlay):
        print(f"bind_tab ${bind_tab:04X} past overlay {len(overlay)}", file=sys.stderr)
        sys.exit(1)

    game = Path(args.game)
    if not game.is_file():
        print(f"missing: {game}", file=sys.stderr)
        sys.exit(1)

    raw = game.read_bytes()
    if len(raw) < 5:
        print(f"{game}: too short", file=sys.stderr)
        sys.exit(1)
    load = raw[0] | (raw[1] << 8)
    body = raw[2:]

    labels = parse_labels(Path(args.labels))
    max_id = 255
    last = "slope_flags" if "slope_flags" in labels else (
        "door_type" if "door_type" in labels else "map_text"
    )
    if "room_x" in labels and last in labels:
        max_id = (labels[last] - labels["room_x"]) // 2
        if max_id < 0 or max_id > 255:
            print("map pointer table field id out of range", file=sys.stderr)
            sys.exit(1)

    recs = scan(body, load, sentinel, max_id)
    if not recs:
        print("mkreloc: zero SMC sites (macros not emitting sentinel?)", file=sys.stderr)
        sys.exit(1)
    if len(recs) < 200:
        print(f"mkreloc: warning: only {len(recs)} sites (expected ~400+)", file=sys.stderr)

    reloc = bytearray()
    reloc += struct.pack("<H", len(recs))
    for addr, _fid in recs:
        reloc += struct.pack("<H", addr)

    prefix = write_prefix_asm(overlay, bytes(reloc), bind_tab)
    pack_maps(overlay, bytes(reloc))
    print(
        f"Prefixed maps ({len(recs)} sites, overlay {len(overlay)}, "
        f"reloc {len(reloc)}, LEVEL_PREFIX {prefix})"
    )


if __name__ == "__main__":
    main()
