; Auto-generated by tools/genlinebodies.py — unrolled Mike 30k bodies
; ---- X major +Y ----
sdn_l	!byte <sd0,<sd1,<sd2,<sd3,<sd4,<sd5,<sd6,<sd7
sdn_h	!byte >sd0,>sd1,>sd2,>sd3,>sd4,>sd5,>sd6,>sd7
sd0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne sd0c
	rts
sd0c
	lda err_l
	sbc dy
	bcs sd0ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd0d
	jsr y_cross_down
	jmp sd0d
sd0ny
	sta err_l
sd0d
	sec
sd1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne sd1c
	rts
sd1c
	lda err_l
	sbc dy
	bcs sd1ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd1d
	jsr y_cross_down
	jmp sd1d
sd1ny
	sta err_l
sd1d
	sec
sd2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne sd2c
	rts
sd2c
	lda err_l
	sbc dy
	bcs sd2ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd2d
	jsr y_cross_down
	jmp sd2d
sd2ny
	sta err_l
sd2d
	sec
sd3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne sd3c
	rts
sd3c
	lda err_l
	sbc dy
	bcs sd3ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd3d
	jsr y_cross_down
	jmp sd3d
sd3ny
	sta err_l
sd3d
	sec
sd4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne sd4c
	rts
sd4c
	lda err_l
	sbc dy
	bcs sd4ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd4d
	jsr y_cross_down
	jmp sd4d
sd4ny
	sta err_l
sd4d
	sec
sd5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne sd5c
	rts
sd5c
	lda err_l
	sbc dy
	bcs sd5ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd5d
	jsr y_cross_down
	jmp sd5d
sd5ny
	sta err_l
sd5d
	sec
sd6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne sd6c
	rts
sd6c
	lda err_l
	sbc dy
	bcs sd6ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd6d
	jsr y_cross_down
	jmp sd6d
sd6ny
	sta err_l
sd6d
	sec
sd7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne sd7c
	rts
sd7c
	lda err_l
	sbc dy
	bcs sd7ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sd7d
	jsr y_cross_down
	jmp sd7d
sd7ny
	sta err_l
sd7d
	sec
	clc
	lda colptr
	adc #64
	sta colptr
	bcc sdcol
	inc colptr+1
sdcol
	sec
	jmp sd0

; ---- X major -Y ----
sup_l	!byte <su0,<su1,<su2,<su3,<su4,<su5,<su6,<su7
sup_h	!byte >su0,>su1,>su2,>su3,>su4,>su5,>su6,>su7
su0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne su0c
	rts
su0c
	lda err_l
	sbc dy
	bcs su0ny
	adc dx
	sta err_l
	dey
	bpl su0d
	jsr y_cross_up
	jmp su0d
su0ny
	sta err_l
su0d
	sec
su1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne su1c
	rts
su1c
	lda err_l
	sbc dy
	bcs su1ny
	adc dx
	sta err_l
	dey
	bpl su1d
	jsr y_cross_up
	jmp su1d
su1ny
	sta err_l
su1d
	sec
su2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne su2c
	rts
su2c
	lda err_l
	sbc dy
	bcs su2ny
	adc dx
	sta err_l
	dey
	bpl su2d
	jsr y_cross_up
	jmp su2d
su2ny
	sta err_l
su2d
	sec
su3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne su3c
	rts
su3c
	lda err_l
	sbc dy
	bcs su3ny
	adc dx
	sta err_l
	dey
	bpl su3d
	jsr y_cross_up
	jmp su3d
su3ny
	sta err_l
su3d
	sec
su4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne su4c
	rts
su4c
	lda err_l
	sbc dy
	bcs su4ny
	adc dx
	sta err_l
	dey
	bpl su4d
	jsr y_cross_up
	jmp su4d
su4ny
	sta err_l
su4d
	sec
su5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne su5c
	rts
su5c
	lda err_l
	sbc dy
	bcs su5ny
	adc dx
	sta err_l
	dey
	bpl su5d
	jsr y_cross_up
	jmp su5d
su5ny
	sta err_l
su5d
	sec
su6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne su6c
	rts
su6c
	lda err_l
	sbc dy
	bcs su6ny
	adc dx
	sta err_l
	dey
	bpl su6d
	jsr y_cross_up
	jmp su6d
su6ny
	sta err_l
su6d
	sec
su7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne su7c
	rts
su7c
	lda err_l
	sbc dy
	bcs su7ny
	adc dx
	sta err_l
	dey
	bpl su7d
	jsr y_cross_up
	jmp su7d
su7ny
	sta err_l
su7d
	sec
	clc
	lda colptr
	adc #64
	sta colptr
	bcc sucol
	inc colptr+1
sucol
	sec
	jmp su0

; ---- Y major +Y ----
std_l	!byte <td0,<td1,<td2,<td3,<td4,<td5,<td6,<td7
std_h	!byte >td0,>td1,>td2,>td3,>td4,>td5,>td6,>td7
td0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne td0c
	rts
td0c
	iny
	cpy #64
	bcc td0e
	jsr y_cross_down
td0e
	sec
	lda err_l
	sbc dx
	bcs td0s
	adc dy
	sta err_l
	jmp td1
td0s
	sta err_l
	jmp td0
td1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne td1c
	rts
td1c
	iny
	cpy #64
	bcc td1e
	jsr y_cross_down
td1e
	sec
	lda err_l
	sbc dx
	bcs td1s
	adc dy
	sta err_l
	jmp td2
td1s
	sta err_l
	jmp td1
td2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne td2c
	rts
td2c
	iny
	cpy #64
	bcc td2e
	jsr y_cross_down
td2e
	sec
	lda err_l
	sbc dx
	bcs td2s
	adc dy
	sta err_l
	jmp td3
td2s
	sta err_l
	jmp td2
td3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne td3c
	rts
td3c
	iny
	cpy #64
	bcc td3e
	jsr y_cross_down
td3e
	sec
	lda err_l
	sbc dx
	bcs td3s
	adc dy
	sta err_l
	jmp td4
td3s
	sta err_l
	jmp td3
td4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne td4c
	rts
td4c
	iny
	cpy #64
	bcc td4e
	jsr y_cross_down
td4e
	sec
	lda err_l
	sbc dx
	bcs td4s
	adc dy
	sta err_l
	jmp td5
td4s
	sta err_l
	jmp td4
td5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne td5c
	rts
td5c
	iny
	cpy #64
	bcc td5e
	jsr y_cross_down
td5e
	sec
	lda err_l
	sbc dx
	bcs td5s
	adc dy
	sta err_l
	jmp td6
td5s
	sta err_l
	jmp td5
td6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne td6c
	rts
td6c
	iny
	cpy #64
	bcc td6e
	jsr y_cross_down
td6e
	sec
	lda err_l
	sbc dx
	bcs td6s
	adc dy
	sta err_l
	jmp td7
td6s
	sta err_l
	jmp td6
td7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne td7c
	rts
td7c
	iny
	cpy #64
	bcc td7e
	jsr y_cross_down
td7e
	sec
	lda err_l
	sbc dx
	bcs td7s
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc td7nc
	inc colptr+1
td7nc
	sec
	jmp td0
td7s
	sta err_l
	jmp td7
; ---- Y major -Y ----
stu_l	!byte <tu0,<tu1,<tu2,<tu3,<tu4,<tu5,<tu6,<tu7
stu_h	!byte >tu0,>tu1,>tu2,>tu3,>tu4,>tu5,>tu6,>tu7
tu0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne tu0c
	rts
tu0c
	dey
	bpl tu0e
	jsr y_cross_up
tu0e
	sec
	lda err_l
	sbc dx
	bcs tu0s
	adc dy
	sta err_l
	jmp tu1
tu0s
	sta err_l
	jmp tu0
tu1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne tu1c
	rts
tu1c
	dey
	bpl tu1e
	jsr y_cross_up
tu1e
	sec
	lda err_l
	sbc dx
	bcs tu1s
	adc dy
	sta err_l
	jmp tu2
tu1s
	sta err_l
	jmp tu1
tu2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne tu2c
	rts
tu2c
	dey
	bpl tu2e
	jsr y_cross_up
tu2e
	sec
	lda err_l
	sbc dx
	bcs tu2s
	adc dy
	sta err_l
	jmp tu3
tu2s
	sta err_l
	jmp tu2
tu3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne tu3c
	rts
tu3c
	dey
	bpl tu3e
	jsr y_cross_up
tu3e
	sec
	lda err_l
	sbc dx
	bcs tu3s
	adc dy
	sta err_l
	jmp tu4
tu3s
	sta err_l
	jmp tu3
tu4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne tu4c
	rts
tu4c
	dey
	bpl tu4e
	jsr y_cross_up
tu4e
	sec
	lda err_l
	sbc dx
	bcs tu4s
	adc dy
	sta err_l
	jmp tu5
tu4s
	sta err_l
	jmp tu4
tu5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne tu5c
	rts
tu5c
	dey
	bpl tu5e
	jsr y_cross_up
tu5e
	sec
	lda err_l
	sbc dx
	bcs tu5s
	adc dy
	sta err_l
	jmp tu6
tu5s
	sta err_l
	jmp tu5
tu6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne tu6c
	rts
tu6c
	dey
	bpl tu6e
	jsr y_cross_up
tu6e
	sec
	lda err_l
	sbc dx
	bcs tu6s
	adc dy
	sta err_l
	jmp tu7
tu6s
	sta err_l
	jmp tu6
tu7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne tu7c
	rts
tu7c
	dey
	bpl tu7e
	jsr y_cross_up
tu7e
	sec
	lda err_l
	sbc dx
	bcs tu7s
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc tu7nc
	inc colptr+1
tu7nc
	sec
	jmp tu0
tu7s
	sta err_l
	jmp tu7
