; Auto-generated by tools/genlinebodies.py — unrolled Mike 30k bodies
; Fast sd/su/td/tu: chained C, no per-pixel CPY. Slow sds/sus: CPY flats.
; ---- X major +Y (fast, same half) ----
sdn_l	!byte <sd0,<sd1,<sd2,<sd3,<sd4,<sd5,<sd6,<sd7
sdn_h	!byte >sd0,>sd1,>sd2,>sd3,>sd4,>sd5,>sd6,>sd7
sd0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne sd0c
	rts
sd0c
	lda err_l
	sbc dy
	bcs sd0sk
	adc dx
	iny
sd0sk
	sta err_l
sd1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne sd1c
	rts
sd1c
	lda err_l
	sbc dy
	bcs sd1sk
	adc dx
	iny
sd1sk
	sta err_l
sd2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne sd2c
	rts
sd2c
	lda err_l
	sbc dy
	bcs sd2sk
	adc dx
	iny
sd2sk
	sta err_l
sd3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne sd3c
	rts
sd3c
	lda err_l
	sbc dy
	bcs sd3sk
	adc dx
	iny
sd3sk
	sta err_l
sd4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne sd4c
	rts
sd4c
	lda err_l
	sbc dy
	bcs sd4sk
	adc dx
	iny
sd4sk
	sta err_l
sd5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne sd5c
	rts
sd5c
	lda err_l
	sbc dy
	bcs sd5sk
	adc dx
	iny
sd5sk
	sta err_l
sd6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne sd6c
	rts
sd6c
	lda err_l
	sbc dy
	bcs sd6sk
	adc dx
	iny
sd6sk
	sta err_l
sd7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne sd7c
	rts
sd7c
	lda err_l
	sbc dy
	bcs sd7sk
	adc dx
	iny
sd7sk
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc sdcol
	inc colptr+1
sdcol
	sec
	jmp sd0

; ---- X major -Y (fast, same half) ----
sup_l	!byte <su0,<su1,<su2,<su3,<su4,<su5,<su6,<su7
sup_h	!byte >su0,>su1,>su2,>su3,>su4,>su5,>su6,>su7
su0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne su0c
	rts
su0c
	lda err_l
	sbc dy
	bcs su0sk
	adc dx
	dey
su0sk
	sta err_l
su1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne su1c
	rts
su1c
	lda err_l
	sbc dy
	bcs su1sk
	adc dx
	dey
su1sk
	sta err_l
su2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne su2c
	rts
su2c
	lda err_l
	sbc dy
	bcs su2sk
	adc dx
	dey
su2sk
	sta err_l
su3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne su3c
	rts
su3c
	lda err_l
	sbc dy
	bcs su3sk
	adc dx
	dey
su3sk
	sta err_l
su4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne su4c
	rts
su4c
	lda err_l
	sbc dy
	bcs su4sk
	adc dx
	dey
su4sk
	sta err_l
su5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne su5c
	rts
su5c
	lda err_l
	sbc dy
	bcs su5sk
	adc dx
	dey
su5sk
	sta err_l
su6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne su6c
	rts
su6c
	lda err_l
	sbc dy
	bcs su6sk
	adc dx
	dey
su6sk
	sta err_l
su7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne su7c
	rts
su7c
	lda err_l
	sbc dy
	bcs su7sk
	adc dx
	dey
su7sk
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc sucol
	inc colptr+1
sucol
	sec
	jmp su0

; ---- X major +Y (slow, crosses y=64) ----
sds_l	!byte <sds0,<sds1,<sds2,<sds3,<sds4,<sds5,<sds6,<sds7
sds_h	!byte >sds0,>sds1,>sds2,>sds3,>sds4,>sds5,>sds6,>sds7
sds0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne sds0c
	rts
sds0c
	lda err_l
	sbc dy
	bcs sds0ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds0d
	jsr y_cross_down
	jmp sds0d
sds0ny
	sta err_l
sds0d
	sec
sds1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne sds1c
	rts
sds1c
	lda err_l
	sbc dy
	bcs sds1ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds1d
	jsr y_cross_down
	jmp sds1d
sds1ny
	sta err_l
sds1d
	sec
sds2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne sds2c
	rts
sds2c
	lda err_l
	sbc dy
	bcs sds2ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds2d
	jsr y_cross_down
	jmp sds2d
sds2ny
	sta err_l
sds2d
	sec
sds3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne sds3c
	rts
sds3c
	lda err_l
	sbc dy
	bcs sds3ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds3d
	jsr y_cross_down
	jmp sds3d
sds3ny
	sta err_l
sds3d
	sec
sds4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne sds4c
	rts
sds4c
	lda err_l
	sbc dy
	bcs sds4ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds4d
	jsr y_cross_down
	jmp sds4d
sds4ny
	sta err_l
sds4d
	sec
sds5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne sds5c
	rts
sds5c
	lda err_l
	sbc dy
	bcs sds5ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds5d
	jsr y_cross_down
	jmp sds5d
sds5ny
	sta err_l
sds5d
	sec
sds6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne sds6c
	rts
sds6c
	lda err_l
	sbc dy
	bcs sds6ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds6d
	jsr y_cross_down
	jmp sds6d
sds6ny
	sta err_l
sds6d
	sec
sds7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne sds7c
	rts
sds7c
	lda err_l
	sbc dy
	bcs sds7ny
	adc dx
	sta err_l
	iny
	cpy #64
	bcc sds7d
	jsr y_cross_down
	jmp sds7d
sds7ny
	sta err_l
sds7d
	sec
	clc
	lda colptr
	adc #64
	sta colptr
	bcc sdscol
	inc colptr+1
sdscol
	sec
	jmp sds0

; ---- X major -Y (slow, crosses y=64) ----
sus_l	!byte <sus0,<sus1,<sus2,<sus3,<sus4,<sus5,<sus6,<sus7
sus_h	!byte >sus0,>sus1,>sus2,>sus3,>sus4,>sus5,>sus6,>sus7
sus0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne sus0c
	rts
sus0c
	lda err_l
	sbc dy
	bcs sus0ny
	adc dx
	sta err_l
	dey
	bpl sus0d
	jsr y_cross_up
	jmp sus0d
sus0ny
	sta err_l
sus0d
	sec
sus1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne sus1c
	rts
sus1c
	lda err_l
	sbc dy
	bcs sus1ny
	adc dx
	sta err_l
	dey
	bpl sus1d
	jsr y_cross_up
	jmp sus1d
sus1ny
	sta err_l
sus1d
	sec
sus2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne sus2c
	rts
sus2c
	lda err_l
	sbc dy
	bcs sus2ny
	adc dx
	sta err_l
	dey
	bpl sus2d
	jsr y_cross_up
	jmp sus2d
sus2ny
	sta err_l
sus2d
	sec
sus3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne sus3c
	rts
sus3c
	lda err_l
	sbc dy
	bcs sus3ny
	adc dx
	sta err_l
	dey
	bpl sus3d
	jsr y_cross_up
	jmp sus3d
sus3ny
	sta err_l
sus3d
	sec
sus4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne sus4c
	rts
sus4c
	lda err_l
	sbc dy
	bcs sus4ny
	adc dx
	sta err_l
	dey
	bpl sus4d
	jsr y_cross_up
	jmp sus4d
sus4ny
	sta err_l
sus4d
	sec
sus5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne sus5c
	rts
sus5c
	lda err_l
	sbc dy
	bcs sus5ny
	adc dx
	sta err_l
	dey
	bpl sus5d
	jsr y_cross_up
	jmp sus5d
sus5ny
	sta err_l
sus5d
	sec
sus6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne sus6c
	rts
sus6c
	lda err_l
	sbc dy
	bcs sus6ny
	adc dx
	sta err_l
	dey
	bpl sus6d
	jsr y_cross_up
	jmp sus6d
sus6ny
	sta err_l
sus6d
	sec
sus7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne sus7c
	rts
sus7c
	lda err_l
	sbc dy
	bcs sus7ny
	adc dx
	sta err_l
	dey
	bpl sus7d
	jsr y_cross_up
	jmp sus7d
sus7ny
	sta err_l
sus7d
	sec
	clc
	lda colptr
	adc #64
	sta colptr
	bcc suscol
	inc colptr+1
suscol
	sec
	jmp sus0

; ---- Y major +Y (fast; rest_cnt split) ----
std_l	!byte <td0,<td1,<td2,<td3,<td4,<td5,<td6,<td7
std_h	!byte >td0,>td1,>td2,>td3,>td4,>td5,>td6,>td7
td0s
	sta err_l
td0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne td0c
	lda rest_cnt
	beq td0rt
	jmp td0spl
td0rt
	rts
td0c
	iny
	lda err_l
	sbc dx
	bcs td0s
	adc dy
td1s
	sta err_l
td1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne td1c
	lda rest_cnt
	beq td1rt
	jmp td1spl
td1rt
	rts
td1c
	iny
	lda err_l
	sbc dx
	bcs td1s
	adc dy
td2s
	sta err_l
td2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne td2c
	lda rest_cnt
	beq td2rt
	jmp td2spl
td2rt
	rts
td2c
	iny
	lda err_l
	sbc dx
	bcs td2s
	adc dy
td3s
	sta err_l
td3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne td3c
	lda rest_cnt
	beq td3rt
	jmp td3spl
td3rt
	rts
td3c
	iny
	lda err_l
	sbc dx
	bcs td3s
	adc dy
td4s
	sta err_l
td4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne td4c
	lda rest_cnt
	beq td4rt
	jmp td4spl
td4rt
	rts
td4c
	iny
	lda err_l
	sbc dx
	bcs td4s
	adc dy
td5s
	sta err_l
td5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne td5c
	lda rest_cnt
	beq td5rt
	jmp td5spl
td5rt
	rts
td5c
	iny
	lda err_l
	sbc dx
	bcs td5s
	adc dy
td6s
	sta err_l
td6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne td6c
	lda rest_cnt
	beq td6rt
	jmp td6spl
td6rt
	rts
td6c
	iny
	lda err_l
	sbc dx
	bcs td6s
	adc dy
td7s
	sta err_l
td7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne td7c
	lda rest_cnt
	beq td7rt
	jmp td7spl
td7rt
	rts
td7c
	iny
	lda err_l
	sbc dx
	bcs td7s
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc td7nc
	inc colptr+1
td7nc
	sec
	jmp td0
td0spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td0ss
	adc dy
	sta err_l
	jmp td1
td0ss
	sta err_l
	jmp td0

td1spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td1ss
	adc dy
	sta err_l
	jmp td2
td1ss
	sta err_l
	jmp td1

td2spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td2ss
	adc dy
	sta err_l
	jmp td3
td2ss
	sta err_l
	jmp td2

td3spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td3ss
	adc dy
	sta err_l
	jmp td4
td3ss
	sta err_l
	jmp td3

td4spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td4ss
	adc dy
	sta err_l
	jmp td5
td4ss
	sta err_l
	jmp td4

td5spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td5ss
	adc dy
	sta err_l
	jmp td6
td5ss
	sta err_l
	jmp td5

td6spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td6ss
	adc dy
	sta err_l
	jmp td7
td6ss
	sta err_l
	jmp td6

td7spl
	tax
	lda #0
	sta rest_cnt
	jsr split_down
	lda err_l
	sbc dx
	bcs td7ss
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc td7sc
	inc colptr+1
td7sc
	sec
	jmp td0
td7ss
	sta err_l
	jmp td7

; ---- Y major -Y (fast; rest_cnt split) ----
stu_l	!byte <tu0,<tu1,<tu2,<tu3,<tu4,<tu5,<tu6,<tu7
stu_h	!byte >tu0,>tu1,>tu2,>tu3,>tu4,>tu5,>tu6,>tu7
tu0s
	sta err_l
tu0
	lda (colptr),y
	ora #$80
	sta (colptr),y
	dex
	bne tu0c
	lda rest_cnt
	beq tu0rt
	jmp tu0spl
tu0rt
	rts
tu0c
	dey
	lda err_l
	sbc dx
	bcs tu0s
	adc dy
tu1s
	sta err_l
tu1
	lda (colptr),y
	ora #$40
	sta (colptr),y
	dex
	bne tu1c
	lda rest_cnt
	beq tu1rt
	jmp tu1spl
tu1rt
	rts
tu1c
	dey
	lda err_l
	sbc dx
	bcs tu1s
	adc dy
tu2s
	sta err_l
tu2
	lda (colptr),y
	ora #$20
	sta (colptr),y
	dex
	bne tu2c
	lda rest_cnt
	beq tu2rt
	jmp tu2spl
tu2rt
	rts
tu2c
	dey
	lda err_l
	sbc dx
	bcs tu2s
	adc dy
tu3s
	sta err_l
tu3
	lda (colptr),y
	ora #$10
	sta (colptr),y
	dex
	bne tu3c
	lda rest_cnt
	beq tu3rt
	jmp tu3spl
tu3rt
	rts
tu3c
	dey
	lda err_l
	sbc dx
	bcs tu3s
	adc dy
tu4s
	sta err_l
tu4
	lda (colptr),y
	ora #$08
	sta (colptr),y
	dex
	bne tu4c
	lda rest_cnt
	beq tu4rt
	jmp tu4spl
tu4rt
	rts
tu4c
	dey
	lda err_l
	sbc dx
	bcs tu4s
	adc dy
tu5s
	sta err_l
tu5
	lda (colptr),y
	ora #$04
	sta (colptr),y
	dex
	bne tu5c
	lda rest_cnt
	beq tu5rt
	jmp tu5spl
tu5rt
	rts
tu5c
	dey
	lda err_l
	sbc dx
	bcs tu5s
	adc dy
tu6s
	sta err_l
tu6
	lda (colptr),y
	ora #$02
	sta (colptr),y
	dex
	bne tu6c
	lda rest_cnt
	beq tu6rt
	jmp tu6spl
tu6rt
	rts
tu6c
	dey
	lda err_l
	sbc dx
	bcs tu6s
	adc dy
tu7s
	sta err_l
tu7
	lda (colptr),y
	ora #$01
	sta (colptr),y
	dex
	bne tu7c
	lda rest_cnt
	beq tu7rt
	jmp tu7spl
tu7rt
	rts
tu7c
	dey
	lda err_l
	sbc dx
	bcs tu7s
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc tu7nc
	inc colptr+1
tu7nc
	sec
	jmp tu0
tu0spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu0ss
	adc dy
	sta err_l
	jmp tu1
tu0ss
	sta err_l
	jmp tu0

tu1spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu1ss
	adc dy
	sta err_l
	jmp tu2
tu1ss
	sta err_l
	jmp tu1

tu2spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu2ss
	adc dy
	sta err_l
	jmp tu3
tu2ss
	sta err_l
	jmp tu2

tu3spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu3ss
	adc dy
	sta err_l
	jmp tu4
tu3ss
	sta err_l
	jmp tu3

tu4spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu4ss
	adc dy
	sta err_l
	jmp tu5
tu4ss
	sta err_l
	jmp tu4

tu5spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu5ss
	adc dy
	sta err_l
	jmp tu6
tu5ss
	sta err_l
	jmp tu5

tu6spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu6ss
	adc dy
	sta err_l
	jmp tu7
tu6ss
	sta err_l
	jmp tu6

tu7spl
	tax
	lda #0
	sta rest_cnt
	jsr split_up
	lda err_l
	sbc dx
	bcs tu7ss
	adc dy
	sta err_l
	clc
	lda colptr
	adc #64
	sta colptr
	bcc tu7sc
	inc colptr+1
tu7sc
	sec
	jmp tu0
tu7ss
	sta err_l
	jmp tu7

