; Auto-generated by tools/genrotate.py — load sin/cos for yaw-only view
; and prime the fast-multiply pointer sets (A=cos, B=sin)
	ldy yaw
	lda COSTAB,y
	sta cs_b
	jsr mulset_a
	lda SINTAB,y
	sta sn_b
	jsr mulset_b
