; Auto-generated by tools/genrotate.py — inlined log|v|+log|trig| products
	ldy yaw
	lda COSTAB,y
	ldy #0
	cmp #0
	bpl tcsp
	ldy #$80
	eor #$ff
	clc
	adc #1
tcsp
	tax
	lda LOGTAB,x
	sta log_cs
	sty sg_cs
	ldy yaw
	lda SINTAB,y
	ldy #0
	cmp #0
	bpl tsnp
	ldy #$80
	eor #$ff
	clc
	adc #1
tsnp
	tax
	lda LOGTAB,x
	sta log_sn
	sty sg_sn
	ldy pitch
	lda COSTAB,y
	ldy #0
	cmp #0
	bpl tcpp
	ldy #$80
	eor #$ff
	clc
	adc #1
tcpp
	tax
	lda LOGTAB,x
	sta log_cp
	sty sg_cp
	ldy pitch
	lda SINTAB,y
	ldy #0
	cmp #0
	bpl tspp
	ldy #$80
	eor #$ff
	clc
	adc #1
tspp
	tax
	lda LOGTAB,x
	sta log_sp
	sty sg_sp
	lda #0
	sta vindex
.rvert
	ldx vindex
	lda vx,x
	ldy #0
	cmp #0
	bpl vxp
	ldy #$80
	eor #$ff
	clc
	adc #1
vxp
	tax
	lda LOGTAB,x
	sta log_x
	sty sg_x
	ldx vindex
	lda vz,x
	ldy #0
	cmp #0
	bpl vzp
	ldy #$80
	eor #$ff
	clc
	adc #1
vzp
	tax
	lda LOGTAB,x
	sta log_z
	sty sg_z
	ldx vindex
	lda vy,x
	sta ry
	ldy #0
	cmp #0
	bpl vyp
	ldy #$80
	eor #$ff
	clc
	adc #1
vyp
	tax
	lda LOGTAB,x
	sta log_y
	sty sg_y
	; rx = x*cs - z*sn
	lda sg_x
	eor sg_cs
	sta mul_sign
	lda log_x
	clc
	adc log_cs
	bcc xcnoc
	cmp #224
	bcc xcchi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp xcgot
xcchi
	adc #32
	tax
	lda ALOGTAB,x
	jmp xcgot
xcnoc
	cmp #224
	bcc xcz
	sbc #224
	tax
	lda ALOGTAB,x
xcgot
	cmp #128
	bcc xcsg
	lda #$7f
xcsg
	bit mul_sign
	bpl xcout
	eor #$ff
	clc
	adc #1
	jmp xcout
xcz
	lda #0
xcout
	sta rx
	lda sg_z
	eor sg_sn
	sta mul_sign
	lda log_z
	clc
	adc log_sn
	bcc zsnoc
	cmp #224
	bcc zschi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp zsgot
zschi
	adc #32
	tax
	lda ALOGTAB,x
	jmp zsgot
zsnoc
	cmp #224
	bcc zsz
	sbc #224
	tax
	lda ALOGTAB,x
zsgot
	cmp #128
	bcc zssg
	lda #$7f
zssg
	bit mul_sign
	bpl zsout
	eor #$ff
	clc
	adc #1
	jmp zsout
zsz
	lda #0
zsout
	sta rot0
	lda rx
	sec
	sbc rot0
	sta rx
	; rz = x*sn + z*cs
	lda sg_x
	eor sg_sn
	sta mul_sign
	lda log_x
	clc
	adc log_sn
	bcc xsnoc
	cmp #224
	bcc xschi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp xsgot
xschi
	adc #32
	tax
	lda ALOGTAB,x
	jmp xsgot
xsnoc
	cmp #224
	bcc xsz
	sbc #224
	tax
	lda ALOGTAB,x
xsgot
	cmp #128
	bcc xssg
	lda #$7f
xssg
	bit mul_sign
	bpl xsout
	eor #$ff
	clc
	adc #1
	jmp xsout
xsz
	lda #0
xsout
	sta rz
	lda sg_z
	eor sg_cs
	sta mul_sign
	lda log_z
	clc
	adc log_cs
	bcc zcnoc
	cmp #224
	bcc zcchi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp zcgot
zcchi
	adc #32
	tax
	lda ALOGTAB,x
	jmp zcgot
zcnoc
	cmp #224
	bcc zcz
	sbc #224
	tax
	lda ALOGTAB,x
zcgot
	cmp #128
	bcc zcsg
	lda #$7f
zcsg
	bit mul_sign
	bpl zcout
	eor #$ff
	clc
	adc #1
	jmp zcout
zcz
	lda #0
zcout
	clc
	adc rz
	sta rz
	lda rz
	ldy #0
	cmp #0
	bpl rzp
	ldy #$80
	eor #$ff
	clc
	adc #1
rzp
	tax
	lda LOGTAB,x
	sta log_rz
	sty sg_rz
	; y' = y*cp - rz*sp
	lda sg_y
	eor sg_cp
	sta mul_sign
	lda log_y
	clc
	adc log_cp
	bcc ycnoc
	cmp #224
	bcc ycchi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp ycgot
ycchi
	adc #32
	tax
	lda ALOGTAB,x
	jmp ycgot
ycnoc
	cmp #224
	bcc ycz
	sbc #224
	tax
	lda ALOGTAB,x
ycgot
	cmp #128
	bcc ycsg
	lda #$7f
ycsg
	bit mul_sign
	bpl ycout
	eor #$ff
	clc
	adc #1
	jmp ycout
ycz
	lda #0
ycout
	sta rot2
	lda sg_rz
	eor sg_sp
	sta mul_sign
	lda log_rz
	clc
	adc log_sp
	bcc rsnoc
	cmp #224
	bcc rschi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp rsgot
rschi
	adc #32
	tax
	lda ALOGTAB,x
	jmp rsgot
rsnoc
	cmp #224
	bcc rsz
	sbc #224
	tax
	lda ALOGTAB,x
rsgot
	cmp #128
	bcc rssg
	lda #$7f
rssg
	bit mul_sign
	bpl rsout
	eor #$ff
	clc
	adc #1
	jmp rsout
rsz
	lda #0
rsout
	sta rot1
	lda rot2
	sec
	sbc rot1
	sta rot2
	; z'' = y*sp + rz*cp
	lda sg_y
	eor sg_sp
	sta mul_sign
	lda log_y
	clc
	adc log_sp
	bcc ysnoc
	cmp #224
	bcc yschi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp ysgot
yschi
	adc #32
	tax
	lda ALOGTAB,x
	jmp ysgot
ysnoc
	cmp #224
	bcc ysz
	sbc #224
	tax
	lda ALOGTAB,x
ysgot
	cmp #128
	bcc yssg
	lda #$7f
yssg
	bit mul_sign
	bpl ysout
	eor #$ff
	clc
	adc #1
	jmp ysout
ysz
	lda #0
ysout
	sta rot0
	lda sg_rz
	eor sg_cp
	sta mul_sign
	lda log_rz
	clc
	adc log_cp
	bcc rcnoc
	cmp #224
	bcc rcchi
	sbc #224
	tax
	lda ALOGTAB+$100,x
	jmp rcgot
rcchi
	adc #32
	tax
	lda ALOGTAB,x
	jmp rcgot
rcnoc
	cmp #224
	bcc rcz
	sbc #224
	tax
	lda ALOGTAB,x
rcgot
	cmp #128
	bcc rcsg
	lda #$7f
rcsg
	bit mul_sign
	bpl rcout
	eor #$ff
	clc
	adc #1
	jmp rcout
rcz
	lda #0
rcout
	clc
	adc rot0
	sta rz
	lda rot2
	sta ry
	ldx vindex
	lda rx
	sta CAM_X,x
	lda ry
	sta CAM_Y,x
	lda rz
	sta CAM_Z,x
	inc vindex
	lda vindex
	cmp #8
	beq +
	jmp .rvert
+
	rts
