; Generated by tools/genenemies.py — do not edit
; Walk clips 0..3 as signed bytes (runtime <<5 → 8.8)
; gx45/gz45 = 45° yaw bake; gy shared
ENEMY_NTYPES	= 2
ENT_GRUNT	= 0
ENT_ROTT	= 1

; --- Grunt ---
grunt_gx
	!byte $fd,$04,$01,$01,$fa,$fd,$08,$04,$fc,$fc,$05,$05,$f6
	!byte $fc,$03,$01,$00,$fa,$fc,$08,$03,$fc,$fa,$04,$05,$f5
	!byte $fd,$04,$01,$01,$fb,$fd,$09,$04,$fc,$fb,$04,$05,$f6
	!byte $fd,$04,$01,$02,$fb,$fe,$08,$04,$fc,$fb,$05,$06,$f7
grunt_gy
	!byte $12,$12,$21,$24,$1a,$15,$18,$16,$0a,$04,$0a,$00,$18
	!byte $10,$10,$1f,$21,$17,$12,$16,$13,$0b,$00,$09,$00,$14
	!byte $12,$12,$21,$25,$1a,$16,$18,$16,$0a,$00,$0c,$06,$19
	!byte $10,$10,$20,$23,$19,$14,$17,$14,$08,$00,$0b,$00,$16
grunt_gz
	!byte $fd,$fd,$01,$07,$05,$0b,$02,$06,$01,$f8,$fd,$f7,$0f
	!byte $fb,$fb,$00,$06,$02,$07,$01,$04,$01,$01,$f9,$f3,$0c
	!byte $fd,$fd,$ff,$04,$04,$0a,$01,$05,$fa,$f6,$03,$f9,$0e
	!byte $fb,$fb,$ff,$04,$03,$09,$ff,$03,$fa,$f3,$02,$02,$0e
grunt_gx45
	!byte $fc,$01,$01,$06,$ff,$06,$07,$07,$fe,$f8,$01,$fd,$04
	!byte $fa,$ff,$01,$04,$fd,$02,$06,$05,$fe,$fc,$fe,$fa,$01
	!byte $fc,$01,$00,$04,$ff,$05,$07,$06,$f9,$f5,$05,$ff,$03
	!byte $fa,$ff,$00,$04,$ff,$05,$05,$05,$f9,$f3,$05,$06,$04
grunt_gz45
	!byte $00,$fb,$00,$04,$08,$0a,$fc,$01,$04,$fd,$fa,$f6,$12
	!byte $ff,$fa,$ff,$04,$06,$08,$fb,$01,$04,$05,$f8,$f3,$10
	!byte $00,$fb,$ff,$02,$06,$09,$fa,$01,$ff,$fc,$ff,$f8,$11
	!byte $ff,$fa,$ff,$01,$06,$08,$fa,$ff,$ff,$fa,$fe,$fd,$10

; --- Rottweiler ---
rott_gx
	!byte $fa,$06,$00,$00,$fa,$f8,$06,$08,$fa,$fa,$06,$06,$08
	!byte $fa,$06,$00,$00,$fa,$f8,$06,$08,$fa,$fa,$06,$06,$08
	!byte $fa,$06,$00,$00,$fa,$f8,$06,$08,$fa,$fa,$06,$06,$08
	!byte $fa,$06,$00,$00,$fa,$f8,$06,$08,$fa,$fa,$06,$06,$08
rott_gy
	!byte $10,$10,$0e,$12,$06,$00,$06,$00,$06,$00,$06,$00,$00
	!byte $10,$10,$0e,$12,$06,$00,$06,$00,$06,$00,$06,$00,$00
	!byte $10,$10,$0e,$12,$06,$00,$06,$00,$06,$00,$06,$00,$00
	!byte $10,$10,$0e,$12,$06,$00,$06,$00,$06,$00,$06,$00,$00
rott_gz
	!byte $f6,$f6,$06,$0c,$04,$08,$06,$0a,$fc,$f8,$f8,$f4,$0a
	!byte $f6,$f6,$06,$0c,$04,$08,$06,$0a,$fc,$f8,$f8,$f4,$0a
	!byte $f6,$f6,$06,$0c,$04,$08,$06,$0a,$fc,$f8,$f8,$f4,$0a
	!byte $f6,$f6,$06,$0c,$04,$08,$06,$0a,$fc,$f8,$f8,$f4,$0a
rott_gx45
	!byte $f5,$fd,$04,$08,$ff,$00,$08,$0d,$f9,$f6,$ff,$fc,$0d
	!byte $f5,$fd,$04,$08,$ff,$00,$08,$0d,$f9,$f6,$ff,$fc,$0d
	!byte $f5,$fd,$04,$08,$ff,$00,$08,$0d,$f9,$f6,$ff,$fc,$0d
	!byte $f5,$fd,$04,$08,$ff,$00,$08,$0d,$f9,$f6,$ff,$fc,$0d
rott_gz45
	!byte $fd,$f5,$04,$08,$07,$0b,$00,$01,$01,$ff,$f6,$f3,$01
	!byte $fd,$f5,$04,$08,$07,$0b,$00,$01,$01,$ff,$f6,$f3,$01
	!byte $fd,$f5,$04,$08,$07,$0b,$00,$01,$01,$ff,$f6,$f3,$01
	!byte $fd,$f5,$04,$08,$07,$0b,$00,$01,$01,$ff,$f6,$f3,$01

enemy_edges
	!byte 0,1,1,2,2,0,2,3,2,4,4,5,2,6,6,7,0,8,8,9,1,10,10,11,7,12

enemy_gx_lo	!byte <grunt_gx, <rott_gx
enemy_gx_hi	!byte >grunt_gx, >rott_gx
enemy_gy_lo	!byte <grunt_gy, <rott_gy
enemy_gy_hi	!byte >grunt_gy, >rott_gy
enemy_gz_lo	!byte <grunt_gz, <rott_gz
enemy_gz_hi	!byte >grunt_gz, >rott_gz
enemy_gx45_lo	!byte <grunt_gx45, <rott_gx45
enemy_gx45_hi	!byte >grunt_gx45, >rott_gx45
enemy_gz45_lo	!byte <grunt_gz45, <rott_gz45
enemy_gz45_hi	!byte >grunt_gz45, >rott_gz45
enemy_far_z	!byte 13, 4		; Grunt, Rott LOD gate (CAM_ZH)

