; Generated by tools/genenemies.py — boot-loaded enemy metadata
!cpu 6510
!to "enemydata.prg", cbm
!source "mem.asm"
*= ENEMY_DATA_BASE
; Generated by tools/genenemies.py — metadata only; poses load from disk
PAIN_MAX	= 4		; variants per type; pain_var_off uses ASL×2

enemy_edges
	!byte 0,1,1,2,2,0,2,3,2,4,4,5,2,6,6,7,0,8,8,9,1,10,10,11,7,12
enemy_edge_vert
	!byte 0,0,0,0,0,0,0,0,0,0,0,0,0
enemy_hp_init	!byte 6, 15, 5, 16, 25, 80, 80, 12, 40

; Two resident rows, copied from the loaded bank. Width 2; variants are slot*4.
; Zeros until patch_enemy_bank. meta_slot_type $ff = empty.
enemy_stand_start	!byte 0, 0
enemy_stand_len	!byte 0, 0
enemy_alert_start	!byte 0, 0
enemy_alert_len	!byte 0, 0
enemy_run_start	!byte 0, 0
enemy_run_len	!byte 0, 0
enemy_walk_start	!byte 0, 0
enemy_walk_len	!byte 0, 0
enemy_attack_n	!byte 0, 0
enemy_attack_start	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_attack_len	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_pain_n	!byte 0, 0
enemy_pain_start	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_pain_len	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_death_n	!byte 0, 0
enemy_death_start	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_death_len	!byte 0, 0, 0, 0, 0, 0, 0, 0
enemy_range	!byte 0, 0
enemy_pain_chance	!byte 0, 0
enemy_drop_type	!byte 0, 0
enemy_fire_frame	!byte 0, 0
enemy_class	!byte 0, 0
enemy_lod_z	!byte 0, 0
enemy_nframes	!byte 0, 0
meta_slot_type	!byte $ff, $ff
meta_scratch	!byte 0

enemy_data_end = *
!if enemy_data_end > ENEMY_DATA_LIMIT {
	!error "Enemy metadata overlaps streamed AI pointers"
}
