; Generated by tools/genenemies.py — do not edit
; Walk clips 0..3 as signed bytes (runtime <<5 → 8.8)
; gx45/gz45 = 45° yaw bake; gy shared
ENEMY_NTYPES	= 2
ENT_GRUNT	= 0
ENT_ROTT	= 1

; --- Grunt ---
grunt_gx
	!byte $fd,$04,$00,$01,$f9,$fa,$08,$04,$fc,$fa,$04,$06,$f5
	!byte $fd,$04,$00,$01,$f9,$fa,$08,$04,$fc,$fa,$04,$06,$f5
	!byte $fd,$04,$00,$01,$f9,$fa,$08,$04,$fc,$fa,$04,$06,$f5
	!byte $fd,$04,$00,$01,$f9,$fa,$08,$04,$fc,$fa,$04,$06,$f5
grunt_gy
	!byte $10,$10,$1e,$21,$16,$11,$15,$13,$08,$00,$0a,$00,$15
	!byte $10,$10,$1e,$21,$16,$11,$15,$13,$08,$00,$0a,$00,$15
	!byte $10,$10,$1e,$21,$16,$11,$15,$13,$08,$00,$0a,$00,$15
	!byte $10,$10,$1e,$21,$16,$11,$15,$13,$08,$00,$0a,$00,$15
grunt_gz
	!byte $fc,$fc,$00,$05,$03,$09,$00,$05,$fe,$f7,$02,$fe,$0c
	!byte $fc,$fc,$00,$05,$03,$09,$00,$05,$fe,$f7,$02,$fe,$0c
	!byte $fc,$fc,$00,$05,$03,$09,$00,$05,$fe,$f7,$02,$fe,$0c
	!byte $fc,$fc,$00,$05,$03,$09,$00,$05,$fe,$f7,$02,$fe,$0d
grunt_gx45
	!byte $fb,$00,$00,$04,$fd,$02,$06,$06,$fc,$f5,$04,$03,$01
	!byte $fb,$00,$00,$04,$fd,$02,$06,$06,$fc,$f5,$04,$03,$01
	!byte $fb,$00,$00,$04,$fd,$02,$06,$06,$fc,$f5,$04,$03,$01
	!byte $fb,$00,$00,$04,$fd,$02,$06,$06,$fc,$f5,$04,$03,$01
grunt_gz45
	!byte $ff,$fa,$00,$03,$07,$0b,$fa,$01,$01,$fe,$ff,$fa,$10
	!byte $ff,$fa,$00,$03,$07,$0b,$fa,$01,$01,$fe,$ff,$fa,$10
	!byte $ff,$fa,$00,$03,$07,$0b,$fa,$01,$01,$fe,$ff,$fa,$10
	!byte $ff,$fa,$00,$03,$07,$0b,$fa,$01,$01,$fe,$ff,$fa,$11

; --- Rottweiler ---
rott_gx
	!byte $fb,$05,$00,$00,$fc,$fc,$05,$05,$fd,$fd,$03,$03,$05
	!byte $fc,$05,$00,$00,$fc,$fc,$05,$05,$fd,$fd,$03,$04,$05
	!byte $fc,$06,$00,$00,$fb,$fb,$05,$05,$fd,$fc,$03,$04,$05
	!byte $fc,$05,$00,$00,$fb,$fb,$05,$04,$fd,$fd,$03,$04,$04
rott_gy
	!byte $15,$16,$0e,$0d,$06,$00,$07,$00,$08,$00,$0a,$05,$00
	!byte $15,$15,$10,$0e,$07,$00,$09,$ff,$08,$00,$09,$01,$ff
	!byte $15,$15,$11,$0f,$07,$00,$0a,$01,$09,$00,$09,$00,$01
	!byte $16,$15,$10,$0d,$07,$00,$08,$01,$09,$02,$08,$ff,$01
rott_gz
	!byte $fa,$fb,$0b,$16,$0b,$13,$ff,$01,$fa,$f6,$fa,$f5,$01
	!byte $f9,$fa,$0a,$15,$07,$0d,$02,$06,$f6,$f3,$fb,$fa,$06
	!byte $f8,$f9,$09,$14,$04,$08,$04,$0a,$f5,$f2,$fc,$fe,$0a
	!byte $f9,$fa,$0a,$15,$02,$05,$08,$0f,$f8,$f3,$fc,$fc,$0f
rott_gx45
	!byte $f8,$00,$08,$10,$05,$0b,$03,$04,$fa,$f7,$fe,$fa,$04
	!byte $f8,$ff,$07,$0f,$02,$06,$05,$08,$f7,$f5,$ff,$ff,$08
	!byte $f8,$ff,$06,$0e,$ff,$02,$06,$0b,$f6,$f3,$ff,$01,$0b
	!byte $f8,$ff,$07,$0f,$fe,$00,$09,$0d,$f8,$f5,$ff,$00,$0d
rott_gz45
	!byte $ff,$f9,$08,$10,$0b,$10,$fc,$fd,$fe,$fb,$fa,$f6,$fd
	!byte $fe,$f8,$07,$0f,$08,$0c,$fe,$01,$fb,$f9,$fa,$f9,$01
	!byte $fd,$f7,$06,$0e,$06,$09,$ff,$04,$fa,$f9,$fb,$fc,$04
	!byte $fe,$f8,$07,$0f,$05,$07,$02,$08,$fc,$f9,$fb,$fa,$08

enemy_edges
	!byte 0,1,1,2,2,0,2,3,2,4,4,5,2,6,6,7,0,8,8,9,1,10,10,11,7,12
enemy_edge_vert
	!byte 0,0,0,0,0,0,0,0,0,0,0,0,0

enemy_gx_lo	!byte <grunt_gx, <rott_gx
enemy_gx_hi	!byte >grunt_gx, >rott_gx
enemy_gy_lo	!byte <grunt_gy, <rott_gy
enemy_gy_hi	!byte >grunt_gy, >rott_gy
enemy_gz_lo	!byte <grunt_gz, <rott_gz
enemy_gz_hi	!byte >grunt_gz, >rott_gz
enemy_gx45_lo	!byte <grunt_gx45, <rott_gx45
enemy_gx45_hi	!byte >grunt_gx45, >rott_gx45
enemy_gz45_lo	!byte <grunt_gz45, <rott_gz45
enemy_gz45_hi	!byte >grunt_gz45, >rott_gz45
enemy_far_z	!byte 13, 4		; Grunt, Rott LOD gate (CAM_ZH)

