; Auto-generated by tools/genenemymuzzle.py — do not edit
; zeromask: 8 occupancy bytes + nonzero payload (24×21 hi-res)
; Distance LOD: 0 = near/large … 2 = far/small
spr_emuz_0
	!byte $90,$24,$ed,$6d,$db,$fe,$6f,$09,$10,$10,$28,$28,$44,$78,$44,$27
	!byte $83,$fe,$10,$04,$08,$18,$06,$20,$01,$c0,$02,$80,$02,$80,$04,$18
	!byte $80,$08,$64,$40,$09,$83,$40,$16,$c0,$18,$40,$20

spr_emuz_1
	!byte $00,$00,$40,$92,$24,$01,$00,$00,$10,$10,$ee,$44,$38,$28,$44

spr_emuz_2
	!byte $00,$00,$00,$92,$24,$00,$00,$00,$10,$10,$7c,$38,$44

