; Auto-generated by tools/genenemylod.py — do not edit
; enemylod.png: 7 of 8x8, index = ent_type
ENEMY_LOD_N	= 7
enemy_lod
	!byte $10,$30,$58,$7e,$68,$38,$28,$28
	!byte $00,$00,$00,$18,$18,$18,$3c,$24
	!byte $00,$00,$00,$00,$00,$00,$00,$00
	!byte $00,$00,$00,$00,$00,$00,$00,$00
	!byte $00,$00,$00,$00,$00,$00,$00,$00
	!byte $00,$00,$00,$00,$00,$00,$00,$00
	!byte $00,$00,$00,$00,$00,$00,$00,$00
