; Generated by tools/genmap.py — do not edit
; E1M1 'The Slipgate Complex'

spawn_x	!byte 1
spawn_y	!byte 106
spawn_z	!byte 119
spawn_rot	!byte 2
spawn_room	!byte 0
spawn_id	!byte 11

room_x
	!byte 0,22,29,94,115,121,140
room_y
	!byte 104,64,65,65,65,78,55
room_z
	!byte 117,124,112,96,160,135,96
room_sx
	!byte 32,6,64,20,24,8,20
room_sy
	!byte 8,48,32,20,20,6,30
room_sz
	!byte 6,16,32,80,16,24,80
room_bg
	!byte 9,2,14,9,6,11,9
room_line
	!byte 7,7,1,7,7,7,7
room_id
	!byte 0,1,9,19,20,28,29

door_x
	!byte 23,28,93,114,123,139
door_y
	!byte 104,65,65,65,78,65
door_z
	!byte 123,135,126,166,159,166
door_sx
	!byte 4,1,1,1,4,1
door_sy
	!byte 5,5,5,5,5,5
door_sz
	!byte 1,4,4,4,1,4
door_ra
	!byte 0,1,2,3,4,4
door_rb
	!byte 1,2,3,4,5,6
door_home_y
	!byte 104,65,65,65,78,65
door_face
	!byte 1,2,2,2,0,2
door_id
	!byte 2,6,13,21,23,27

crate_x
	!byte 0,22,60
crate_y
	!byte 104,64,84
crate_z
	!byte 118,124,112
crate_sx
	!byte 4,6,6
crate_sy
	!byte 2,40,4
crate_sz
	!byte 4,10,32
crate_room
	!byte 0,1,2
crate_id
	!byte 3,5,14

slope_x
	!byte 4
slope_y
	!byte 104
slope_z
	!byte 118
slope_sx
	!byte 4
slope_sy
	!byte 2
slope_sz
	!byte 4
slope_axis
	!byte 0
slope_dir
	!byte 0
slope_room
	!byte 0
slope_id
	!byte 10

plat_x
	!byte 22,22,123,140,140
plat_y
	!byte 77,92,78,65,65
plat_z
	!byte 134,134,160,136,96
plat_sx
	!byte 6,6,4,20,20
plat_sz
	!byte 6,6,12,40,20
plat_room
	!byte 1,1,4,6,6
plat_solid
	!byte 0,0,1,1,1
plat_id
	!byte 16,17,24,30,31

elev_x
	!byte 22,123,140
elev_y0
	!byte 103,77,55
elev_z
	!byte 134,172,116
elev_sx
	!byte 6,4,10
elev_sy
	!byte 1,1,1
elev_sz
	!byte 6,4,20
elev_type
	!byte 2,2,2
elev_home
	!byte 103,77,64
elev_dest
	!byte 64,65,55
elev_room
	!byte 1,4,6
elev_id
	!byte 8,25,33

sw_x
	!byte 24,22,121,140,124
sw_y
	!byte 105,66,67,66,79
sw_z
	!byte 139,136,175,145,175
sw_sx
	!byte 2,1,2,1,2
sw_sy
	!byte 3,3,3,3,3
sw_sz
	!byte 1,2,1,2,1
sw_elev
	!byte 0,0,1,2,1
sw_room
	!byte 1,1,4,6,4
sw_face
	!byte 0,3,0,3,0
sw_id
	!byte 7,18,26,32,37

en_x
	!byte 83,83,108,155,145
en_y
	!byte 65,65,65,65,65
en_z
	!byte 120,135,128,102,106
en_type
	!byte 0,1,0,0,0
en_rot
	!byte 6,6,6,0,0
en_room
	!byte 2,2,3,6,6
en_id
	!byte 4,12,22,35,36

tr_x
	!byte 11
tr_y
	!byte 104
tr_z
	!byte 117
tr_sx
	!byte 6
tr_sy
	!byte 6
tr_sz
	!byte 6
tr_room
	!byte 0
tr_text_off
	!byte 0
tr_id
	!byte 15

bp_x
	!byte 124
bp_y
	!byte 78
bp_z
	!byte 136
bp_type
	!byte 1
bp_room
	!byte 5
bp_id
	!byte 34

map_text
	!byte 84,104,101,32,83,108,105,112,103,97,116,101,32,67,111,109,112,108,101,120,0

