; Generated by tools/genmap.py — do not edit
; E1M1 'The Slipgate Complex'

spawn_x	!byte 1
spawn_y	!byte 106
spawn_z	!byte 119
spawn_rot	!byte 2
spawn_room	!byte 0

room_x
	!byte 0,22,29
room_y
	!byte 104,64,65
room_z
	!byte 117,124,112
room_sx
	!byte 32,6,64
room_sy
	!byte 8,48,32
room_sz
	!byte 6,16,32
room_sky
	!byte 9,2,14
room_floor
	!byte 9,2,5
room_line
	!byte 7,7,1

door_x
	!byte 23,28,93
door_y
	!byte 104,65,65
door_z
	!byte 123,135,126
door_sx
	!byte 4,1,1
door_sy
	!byte 5,5,5
door_sz
	!byte 1,4,4
door_ra
	!byte 0,1,2
door_rb
	!byte 1,2,255
door_home_y
	!byte 104,65,65
door_face
	!byte 1,2,2

crate_x
	!byte 0,22,60
crate_y
	!byte 104,64,84
crate_z
	!byte 118,124,112
crate_sx
	!byte 4,6,6
crate_sy
	!byte 2,40,4
crate_sz
	!byte 4,10,32
crate_room
	!byte 0,1,2

slope_x
	!byte 4
slope_y
	!byte 104
slope_z
	!byte 118
slope_sx
	!byte 4
slope_sy
	!byte 2
slope_sz
	!byte 4
slope_axis
	!byte 0
slope_dir
	!byte 0
slope_room
	!byte 0

plat_x
	!byte 22,22
plat_y
	!byte 77,92
plat_z
	!byte 134,134
plat_sx
	!byte 6,6
plat_sz
	!byte 6,6
plat_room
	!byte 1,1
plat_solid
	!byte 0,0

elev_x
	!byte 22
elev_y0
	!byte 103
elev_z
	!byte 134
elev_sx
	!byte 6
elev_sy
	!byte 1
elev_sz
	!byte 6
elev_type
	!byte 2
elev_home
	!byte 103
elev_dest
	!byte 64
elev_room
	!byte 1

sw_x
	!byte 24,22
sw_y
	!byte 105,66
sw_z
	!byte 139,136
sw_sx
	!byte 2,1
sw_sy
	!byte 3,3
sw_sz
	!byte 1,2
sw_elev
	!byte 0,0
sw_room
	!byte 1,1
sw_face
	!byte 0,2

en_x
	!byte 83,83
en_y
	!byte 65,65
en_z
	!byte 120,135
en_type
	!byte 0,1
en_rot
	!byte 6,6
en_room
	!byte 2,2

tr_x
	!byte 11
tr_y
	!byte 104
tr_z
	!byte 117
tr_sx
	!byte 6
tr_sy
	!byte 6
tr_sz
	!byte 6
tr_room
	!byte 0
tr_text_off
	!byte 0

map_text
	!byte 84,104,101,32,83,108,105,112,103,97,116,101,32,67,111,109,112,108,101,120,0

