; Generated by tools/genmap.py — do not edit
; E1M1 'The Slipgate Complex'

spawn_x	!byte 3
spawn_y	!byte 105
spawn_z	!byte 119
spawn_rot	!byte 2
spawn_room	!byte 0
spawn_id	!byte 9

room_x
	!byte 2,19,32,94,115,121,140
room_y
	!byte 104,65,53,65,65,78,55
room_z
	!byte 105,124,112,96,160,135,96
room_sx
	!byte 32,12,61,20,24,8,20
room_sy
	!byte 8,47,32,20,20,6,30
room_sz
	!byte 18,16,32,80,16,24,80
room_bg
	!byte 9,2,5,9,6,0,9
room_line
	!byte 7,7,7,7,7,7,7
room_fx
	!byte 1,1,1,1,1,1,1
room_wpn
	!byte 0,0,0,0,0,12,0
room_id
	!byte 0,1,8,16,17,25,26

rc_x
	!byte 2,28,19,19,32,64,94,0,115,0,121,0,140,140
rc_y
	!byte 104,104,104,65,65,53,65,0,65,0,78,0,65,55
rc_z
	!byte 117,105,124,134,112,112,96,0,160,0,135,0,96,116
rc_sx
	!byte 32,6,12,12,61,8,20,0,24,0,8,0,20,20
rc_sy
	!byte 8,8,8,39,20,12,20,0,20,0,6,0,20,10
rc_sz
	!byte 6,12,16,6,32,32,80,0,16,0,24,0,80,20
room_nv
	!byte 14,14,16,0,0,0,16
room_ne
	!byte 20,20,24,0,0,0,24
room_vo
	!byte 0,14,28,0,0,0,44
room_eo
	!byte 0,20,40,0,0,0,64
room_nx
	!byte 3,2,4,0,0,0,2
room_nz
	!byte 3,3,2,0,0,0,4
room_uo
	!byte 0,3,5,0,0,0,9
room_zo
	!byte 0,3,6,0,0,0,8
room_ux
	!byte 2,34,28,19,31,32,93,64,72,140,160
room_uz
	!byte 117,123,105,124,140,134,112,144,96,176,116,136
room_vy
	!byte 104,112,112,104,104,112,112,104,104,112,104,112,104,112,104,112
	!byte 112,104,104,112,112,104,104,104,65,65,65,65,65,85,85,65
	!byte 65,85,85,65,65,65,65,65,53,53,53,53,65,85,85,65
	!byte 65,85,85,65,65,65,65,65,55,55,55,55
room_xid
	!byte 0,0,0,0,1,1,1,1,2,2,2,2,1,1,0,0
	!byte 0,0,1,1,1,1,1,0,0,0,1,1,0,0,0,0
	!byte 1,1,1,1,2,2,3,3,2,2,3,3,0,0,0,0
	!byte 1,1,1,1,1,0,0,1,0,0,1,1
room_zid
	!byte 0,0,1,1,0,0,1,1,0,0,2,2,2,2,0,0
	!byte 1,1,0,0,1,1,2,2,2,1,2,1,0,0,1,1
	!byte 0,0,1,1,0,1,0,1,0,1,0,1,0,0,1,1
	!byte 0,0,1,1,2,2,3,3,2,3,2,3
room_col
	!byte 0,0,1,1,2,2,3,3,4,4,5,5,6,6,0,0
	!byte 1,1,2,2,3,3,4,5,5,1,4,3,0,0,1,1
	!byte 2,2,3,3,4,5,6,7,4,5,6,7,0,0,1,1
	!byte 2,2,3,3,4,5,6,7,5,6,4,7
room_e0
	!byte 0,1,2,0,5,6,4,0,3,1,2,8,10,9,8,12
	!byte 5,4,10,11,0,1,2,0,4,5,6,4,0,8,1,2
	!byte 9,3,10,8,7,12,10,11,0,1,2,0,4,5,6,4
	!byte 0,8,3,4,7,10,1,2,8,9,12,10,11,14,12,13
	!byte 0,1,2,3,0,4,5,6,7,4,0,8,10,3,1,2
	!byte 9,10,12,8,11,14,12,13
room_e1
	!byte 1,2,3,3,6,7,7,8,7,9,6,9,11,11,10,13
	!byte 13,12,12,13,1,2,3,9,5,6,7,8,4,9,5,6
	!byte 10,11,11,12,13,13,12,13,1,2,3,3,5,6,7,7
	!byte 8,9,9,10,11,11,5,6,12,13,13,14,15,15,14,15
	!byte 1,2,3,10,9,5,6,7,11,8,4,9,11,7,5,6
	!byte 12,13,13,14,15,15,14,15
room_evert
	!byte 1,0,1,0,0,1,0,0,0,0,0,1,1,0,0,1
	!byte 0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0
	!byte 1,1,0,1,1,0,0,0,1,0,1,0,1,0,1,0
	!byte 0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0
	!byte 1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0
	!byte 1,1,0,1,1,0,0,0
room_efaces
	!byte 1,9,33,5,10,34,6,4,36,8,40,0,16,8,4,18
	!byte 10,6,20,24,17,9,33,1,18,10,34,2,16,0,24,40
	!byte 1,33,5,2,34,6,4,36,17,9,33,1,18,10,34,2
	!byte 16,0,32,16,32,0,24,40,16,32,4,16,32,4,20,36
	!byte 17,9,33,1,1,18,10,34,2,2,16,0,0,32,24,40
	!byte 1,1,5,2,2,6,4,4

door_x
	!byte 23,31,93,114,123,139
door_y
	!byte 104,65,65,65,78,65
door_z
	!byte 123,135,126,166,159,166
door_sx
	!byte 4,1,1,1,4,1
door_sy
	!byte 5,5,5,5,5,5
door_sz
	!byte 1,4,4,4,1,4
door_ra
	!byte 0,1,3,4,5,4
door_rb
	!byte 1,2,2,3,4,6
door_home_y
	!byte 104,65,65,65,78,65
door_face
	!byte 0,2,3,2,0,2
door_id
	!byte 2,5,11,18,20,24

crate_x
	!byte 2
crate_y
	!byte 104
crate_z
	!byte 118
crate_sx
	!byte 4
crate_sy
	!byte 1
crate_sz
	!byte 4
crate_room
	!byte 0
crate_id
	!byte 3

slope_x
slope_y
slope_z
slope_sx
slope_sy
slope_sz
slope_axis
slope_dir
slope_room
slope_id

plat_x
	!byte 19,19,123,64
plat_y
	!byte 77,92,78,65
plat_z
	!byte 134,134,160,125
plat_sx
	!byte 12,12,4,8
plat_sz
	!byte 6,6,12,4
plat_room
	!byte 1,1,4,2
plat_solid
	!byte 0,0,1,1
plat_id
	!byte 13,14,21,34

elev_x
	!byte 19,123,140
elev_y0
	!byte 103,77,55
elev_z
	!byte 134,172,116
elev_sx
	!byte 6,4,10
elev_sy
	!byte 1,1,1
elev_sz
	!byte 6,4,20
elev_type
	!byte 2,2,2
elev_home
	!byte 103,77,64
elev_dest
	!byte 65,65,55
elev_room
	!byte 1,4,6
elev_id
	!byte 7,22,28

sw_x
	!byte 21,21,121,140,124
sw_y
	!byte 105,66,67,66,79
sw_z
	!byte 139,139,175,145,175
sw_sx
	!byte 2,2,2,1,2
sw_sy
	!byte 3,3,3,3,3
sw_sz
	!byte 1,1,1,2,1
sw_elev
	!byte 0,0,1,2,1
sw_room
	!byte 1,1,4,6,4
sw_face
	!byte 0,0,0,3,0
sw_id
	!byte 6,15,23,27,32

en_x
	!byte 83,83,108,155,145
en_y
	!byte 64,64,65,65,65
en_z
	!byte 120,135,128,102,106
en_type
	!byte 0,1,0,0,0
en_rot
	!byte 6,6,6,0,0
en_room
	!byte 2,2,3,6,6
en_id
	!byte 4,10,19,30,31

tr_x
	!byte 2
tr_y
	!byte 104
tr_z
	!byte 117
tr_sx
	!byte 18
tr_sy
	!byte 6
tr_sz
	!byte 6
tr_room
	!byte 0
tr_text_off
	!byte 0
tr_id
	!byte 12

bp_x
	!byte 124
bp_y
	!byte 78
bp_z
	!byte 136
bp_type
	!byte 1
bp_room
	!byte 5
bp_id
	!byte 29

map_name
	!byte 84,104,101,32,83,108,105,112,103,97,116,101,32,67,111,109,112,108,101,120,0

map_text
	!byte 84,104,101,32,83,108,105,112,103,97,116,101,32,67,111,109,112,108,101,120,0

