; Auto-generated by tools/gen_menu_wip_sprite.py
WIP_SPR_COUNT	= 1
WIP_SPR_W	= 24

menu_wip_spr
	!byte $36,$39,$a3,$76,$35,$a7,$56,$35,$e5,$f6,$b9,$af,$b7,$b1,$ab,$00
	!byte $00,$00,$f3,$5b,$0e,$db,$5b,$0d,$f3,$5b,$0d,$db,$5b,$2d,$f1,$9b
	!byte $ee,$00,$00,$00,$00,$7e,$00,$17,$7e,$e8,$00,$00,$00,$da,$30,$f8
	!byte $da,$30,$cc,$de,$30,$cc,$fe,$30,$cc,$6d,$b6,$fb,$45,$b6,$c3,$00

