; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root
; credits.txt / readthis.txt / ending.txt pages split on lines that are only '^'

control_text
	!scr "^WASD....^ Forward/backward/strafe",0
	!scr "^JL......^ Turn",0
	!scr "^Space...^ Fire",0
	!scr "^K.......^ Use switch (triangle)",0
	!scr "^1234....^ Change weapon",0
	!scr " ",0
	!scr "If you have a mouse in port 1 and",0
	!scr "you have enabled it in the options,",0
	!scr "you can turn and shoot with it.",0
	!scr " ",0
	!scr "Walk into doors to open them.",0
	!scr "Walk over items to pick them up.",0
	!byte 0

order_text
	!scr "Episodes 2 through 4 are",0
	!scr "not available in this",0
	!scr "shareware version.",0
	!scr " ",0
	!scr "All four episodes can be",0
	!scr "ordered by calling",0
	!scr " ",0
	!scr "1-800-id-games",0
	!byte 0

CREDITS_PAGES = 3

credits1_text
	!scr "Quake is a trademark of",0
	!scr "id software llc/zenimax media inc.",0
	!scr " ",0
	!scr "Unofficial commodore 64 fan port",0
	!scr "created by steve mccrea in 2026.",0
	!scr " ",0
	!scr "Not affiliated with or endorsed",0
	!scr "by id software or zenimax.",0
	!scr " ",0
	!scr "For non-commercial/fan use only.",0
	!byte 0

credits2_text
	!scr "Quake was created by",0
	!scr "john carmack, michael abrash,",0
	!scr "john cash, john romero,",0
	!scr "american mcgee, sandy petersen,",0
	!scr "tim willits, adrian carmack,",0
	!scr "kevin cloud, paul steed,",0
	!scr "trent reznor & nine inch nails.",0
	!byte 0

credits3_text
	!scr "Loader by krill / plush.",0
	!scr "Loader integration by chris masiero.",0
	!scr " ",0
	!scr "Thanks all!",0
	!scr " ",0
	!scr "quake64 v0.40.0",0
	!byte 0

credits_lo
	!byte <credits1_text, <credits2_text, <credits3_text
credits_hi
	!byte >credits1_text, >credits2_text, >credits3_text

READTHIS_PAGES = 6

readthis1_text
	!scr "You get the phone call at 0400.",0
	!scr "the commander explains: \"it's about",0
	!scr "the slipgate device. once we perfect",0
	!scr "these, we'll be able to transport people",0
	!scr "and cargo instantly.",0
	!byte 0

readthis2_text
	!scr "\"An enemy codenamed quake is using his",0
	!scr "own slipgates to drop death squads",0
	!scr "inside our bases to steal, kidnap,",0
	!scr "and kill.",0
	!byte 0

readthis3_text
	!scr "\"The hell of it is we have no idea",0
	!scr "where he's from. our top scientists",0
	!scr "think quake's not from earth, but",0
	!scr "another dimension. they say he's",0
	!scr "preparing to unleash his real army,",0
	!scr "whatever that is.",0
	!byte 0

readthis4_text
	!scr "\"You're our best man. this is operation",0
	!scr "counterstrike and you're in charge.",0
	!scr "find quake, and stop him... or it...",0
	!scr "you have full authority to requisition",0
	!scr "anything you need. if the eggheads are",0
	!scr "right, all our lives are expendable.\"",0
	!byte 0

readthis5_text
	!scr "Prelude To Destruction",0
	!scr " ",0
	!scr "As you approach the base, you hear shots.",0
	!scr "damn, that quake bastard works fast!",0
	!scr "he heard about operation counterstrike,",0
	!scr "and hit first. the place is overrun.",0
	!scr "operation counterstrike is over.",0
	!scr "except for you.",0
	!byte 0

readthis6_text
	!scr "The heart of the installation holds a",0
	!scr "slipgate. since quake's killers came",0
	!scr "through, it's paired with his dimension.",0
	!scr "maybe you can get to the asshole",0
	!scr "personally. you pump a round into your",0
	!scr "shotgun, and get moving.",0
	!byte 0

readthis_lo
	!byte <readthis1_text, <readthis2_text, <readthis3_text, <readthis4_text, <readthis5_text, <readthis6_text
readthis_hi
	!byte >readthis1_text, >readthis2_text, >readthis3_text, >readthis4_text, >readthis5_text, >readthis6_text

ENDING_PAGES = 2

ending1_text
	!scr "As the corpse of the monstrous entity",0
	!scr "chthon sinks back into the lava whence",0
	!scr "it rose, you grip the rune of earth magic",0
	!scr "tightly. now that you have conquered",0
	!scr "the dimension of the doomed, realm of",0
	!scr "earth magic, you are ready to complete",0
	!scr "your task.",0
	!byte 0

ending2_text
	!scr "A rune of magic power lies at the end",0
	!scr "of each haunted land of quake. go forth",0
	!scr "and seek the totality of the four runes!",0
	!byte 0

ending_lo
	!byte <ending1_text, <ending2_text
ending_hi
	!byte >ending1_text, >ending2_text
