; Autogenerated by tools/gensounds.py from editor/quake64.json.
; Each effect: N, AD (attack<<4, decay 0), freq[0..N-1], vol[0..N-1] (pulse, same Y).
; freq = Wolf inverse-freq (0 = silence); vol = SID sustain nibble 0..15.
; SOUND_* = FOLDER_STEM from the WAV path (sound/dog/ddeath.wav → SOUND_DOG_DDEATH).
; Streamed enemy cues live on pose PRGs; sound_table hi=0 until bind.

!zone pcsounds

SOUND_WEAPONS_TINK1	= 0
SOUND_PLAYER_DEATH1	= 1
SOUND_DOG_DDEATH	= 2
SOUND_PLAYER_PAIN1	= 3
SOUND_DOORS_HYDRO1	= 4
SOUND_SOLDIER_SIGHT1	= 5
SOUND_WEAPONS_SPIKE2	= 6
SOUND_WEAPONS_LHIT	= 7
SOUND_SOLDIER_DEATH1	= 8
SOUND_WEAPONS_GRENADE	= 9
SOUND_DOG_DSIGHT	= 10
SOUND_ITEMS_ITEMBK2	= 11
SOUND_WEAPONS_PKUP	= 12
SOUND_ITEMS_HEALTH1	= 13
SOUND_MISC_MENU2	= 14
SOUND_ITEMS_DAMAGE	= 15
SOUND_WEAPONS_SHOTGN2	= 16
SOUND_WEAPONS_R_EXP3	= 17
SOUND_OGRE_OGSAWATK	= 18
SOUND_OGRE_OGDRAG	= 19
SOUND_PLAYER_LAND	= 20
SOUND_DOG_DPAIN1	= 21
SOUND_SOLDIER_PAIN1	= 22
SOUND_DOG_DATTACK1	= 23
SOUND_DOG_IDLE	= 24
SOUND_SOLDIER_SATTCK1	= 25
SOUND_WIZARD_WATTACK	= 26
SOUND_WIZARD_WDEATH	= 27
SOUND_WIZARD_WPAIN	= 28
SOUND_WIZARD_WSIGHT	= 29
SOUND_COUNT	= 30

pc_weapons_tink1
	!byte 5, 0, 52, 43, 40, 42, 52, 15, 9, 5, 3, 2
pc_player_death1
	!byte 44, 0, 0, 54, 45, 41, 38, 40, 37, 36, 36, 37, 35, 33, 33, 34
	!byte 33, 33, 31, 28, 33, 32, 29, 29, 28, 28, 27, 28, 33, 30, 26, 26
	!byte 35, 36, 33, 35, 32, 28, 32, 36, 31, 27, 34, 32, 31, 31, 0, 4
	!byte 6, 10, 15, 12, 13, 11, 11, 11, 12, 13, 13, 10, 10, 8, 7, 8
	!byte 4, 3, 5, 5, 5, 5, 3, 2, 2, 2, 3, 3, 2, 2, 3, 3
	!byte 3, 4, 2, 1, 1, 1, 1, 2, 2, 1
pc_player_pain1
	!byte 15, 0, 122, 56, 57, 67, 49, 65, 69, 58, 49, 54, 94, 52, 73, 63
	!byte 67, 3, 8, 8, 14, 8, 15, 12, 9, 3, 3, 4, 5, 3, 1, 1
pc_doors_hydro1
	!byte 12, 0, 119, 118, 118, 116, 114, 111, 107, 101, 95, 89, 83, 77, 15, 15
	!byte 15, 15, 15, 15, 15, 15, 15, 15, 15, 15
pc_weapons_spike2
	!byte 4, 0, 104, 107, 101, 123, 15, 15, 15, 15
pc_weapons_lhit
	!byte 10, 0, 130, 25, 33, 78, 26, 18, 18, 25, 0, 32, 15, 15, 15, 15
	!byte 15, 15, 15, 15, 15, 15
pc_weapons_grenade
	!byte 37, 0, 0, 249, 81, 48, 75, 77, 249, 249, 249, 184, 90, 72, 249, 101
	!byte 249, 50, 0, 249, 187, 249, 85, 101, 68, 0, 83, 249, 213, 93, 0, 249
	!byte 245, 249, 236, 249, 118, 89, 249, 0, 15, 14, 7, 9, 7, 12, 8, 11
	!byte 6, 5, 3, 14, 5, 10, 2, 12, 4, 4, 3, 2, 2, 2, 4, 1
	!byte 2, 2, 1, 5, 2, 2, 2, 2, 2, 1, 1, 2
pc_items_itembk2
	!byte 44, 0, 88, 96, 98, 75, 77, 67, 93, 51, 100, 60, 63, 62, 67, 64
	!byte 55, 72, 49, 70, 51, 63, 89, 70, 64, 66, 72, 107, 64, 109, 69, 91
	!byte 87, 73, 75, 50, 67, 56, 51, 35, 157, 100, 103, 90, 91, 90, 1, 2
	!byte 3, 2, 3, 3, 4, 2, 5, 4, 4, 4, 5, 7, 7, 6, 7, 8
	!byte 7, 9, 10, 7, 7, 7, 8, 13, 8, 15, 9, 12, 14, 5, 5, 5
	!byte 6, 4, 4, 4, 4, 4, 3, 3, 1, 1
pc_weapons_pkup
	!byte 22, 0, 45, 50, 60, 57, 41, 44, 38, 55, 56, 40, 38, 48, 56, 75
	!byte 85, 82, 77, 87, 101, 64, 51, 45, 5, 10, 7, 7, 8, 13, 7, 10
	!byte 7, 9, 9, 13, 15, 13, 8, 4, 3, 2, 3, 1, 1, 1
pc_items_health1
	!byte 31, 0, 63, 74, 67, 56, 58, 71, 59, 85, 73, 74, 53, 52, 50, 62
	!byte 92, 80, 70, 58, 51, 63, 73, 80, 74, 79, 60, 71, 55, 52, 60, 58
	!byte 72, 7, 7, 15, 9, 6, 4, 7, 9, 14, 13, 8, 6, 15, 7, 10
	!byte 13, 14, 8, 7, 5, 7, 13, 10, 8, 6, 3, 2, 2, 2, 1, 1
pc_misc_menu2
	!byte 3, 0, 114, 60, 114, 15, 15, 15
pc_items_damage
	!byte 104, 0, 0, 45, 40, 54, 52, 45, 47, 48, 50, 40, 39, 46, 41, 56
	!byte 42, 45, 42, 47, 45, 47, 46, 44, 45, 44, 44, 60, 44, 66, 56, 45
	!byte 51, 46, 53, 46, 42, 40, 59, 45, 47, 45, 41, 63, 48, 48, 49, 48
	!byte 42, 43, 41, 40, 51, 47, 41, 46, 43, 43, 44, 39, 41, 38, 51, 50
	!byte 48, 40, 42, 49, 47, 41, 42, 51, 42, 55, 43, 46, 49, 42, 42, 47
	!byte 41, 60, 61, 44, 47, 47, 51, 46, 45, 43, 51, 44, 48, 38, 41, 41
	!byte 38, 50, 56, 41, 51, 58, 61, 48, 40, 40, 0, 1, 1, 2, 2, 3
	!byte 2, 4, 4, 5, 6, 6, 6, 7, 7, 7, 10, 8, 10, 9, 11, 12
	!byte 11, 11, 9, 12, 14, 10, 9, 8, 11, 12, 15, 13, 8, 10, 11, 11
	!byte 9, 10, 9, 12, 11, 11, 9, 11, 12, 7, 11, 12, 12, 12, 10, 10
	!byte 10, 10, 9, 13, 11, 10, 10, 9, 7, 7, 10, 10, 10, 11, 10, 11
	!byte 9, 9, 10, 11, 9, 10, 8, 9, 10, 7, 10, 11, 10, 10, 8, 8
	!byte 8, 9, 7, 8, 5, 5, 6, 5, 5, 4, 3, 3, 3, 2, 2, 2
	!byte 1, 1
pc_weapons_shotgn2
	!byte 16, 0, 40, 57, 49, 60, 48, 52, 64, 68, 57, 74, 78, 81, 72, 70
	!byte 83, 107, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15
	!byte 15, 15
pc_weapons_r_exp3
	!byte 73, 0, 69, 69, 109, 249, 85, 249, 102, 207, 246, 249, 86, 249, 77, 86
	!byte 76, 90, 81, 110, 66, 76, 159, 57, 112, 113, 69, 208, 67, 108, 98, 69
	!byte 64, 52, 117, 126, 86, 145, 90, 75, 57, 84, 49, 90, 66, 81, 74, 87
	!byte 52, 81, 94, 73, 85, 74, 83, 80, 81, 87, 80, 54, 79, 77, 59, 93
	!byte 60, 61, 71, 0, 0, 79, 90, 81, 94, 0, 0, 11, 14, 11, 14, 11
	!byte 12, 15, 15, 15, 15, 4, 14, 9, 14, 11, 13, 10, 9, 10, 9, 14
	!byte 12, 13, 14, 10, 10, 7, 11, 10, 5, 6, 7, 11, 10, 10, 12, 6
	!byte 11, 6, 12, 7, 9, 7, 9, 9, 9, 4, 9, 7, 3, 6, 4, 5
	!byte 2, 3, 4, 4, 3, 6, 5, 5, 5, 5, 7, 4, 6, 8, 4, 3
	!byte 2, 2, 1, 2
pc_player_land
	!byte 4, 0, 83, 78, 78, 85, 15, 15, 15, 15

; resident sound payload 878 bytes
sound_priorities
	!byte 1, 99, 50, 90, 20, 50, 50, 50, 50, 20, 50, 90, 80, 85, 1, 70
	!byte 50, 50, 20, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50

; 0 = player V1, 1 = enemy V2, 2 = world V3 (mixer; all pulse)
sound_voices
	!byte 0, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0
	!byte 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0

; 1 = payload on pose heap (sound_table patched at room stream)
sound_streamed
	!byte 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0
	!byte 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1

sound_table
	!word pc_weapons_tink1
	!word pc_player_death1
	!word 0
	!word pc_player_pain1
	!word pc_doors_hydro1
	!word 0
	!word pc_weapons_spike2
	!word pc_weapons_lhit
	!word 0
	!word pc_weapons_grenade
	!word 0
	!word pc_items_itembk2
	!word pc_weapons_pkup
	!word pc_items_health1
	!word pc_misc_menu2
	!word pc_items_damage
	!word pc_weapons_shotgn2
	!word pc_weapons_r_exp3
	!word 0
	!word 0
	!word pc_player_land
	!word 0
	!word 0
	!word 0
	!word 0
	!word 0
	!word 0
	!word 0
	!word 0
	!word 0
