; Auto-generated by tools/gensplat.py — do not edit
; zeromask: 8 occupancy bytes + nonzero payload (24×21 hi-res)
; Distance LOD: 0 = near/large … 2 = far/small
; Source: assets/weapons/splat_0..2.png (ink centered for tip−12/−10)
spr_splat_0
	!byte $00,$20,$6d,$76,$66,$09,$02,$00,$0d,$0c,$01,$88,$01,$c8,$63,$40
	!byte $11,$c0,$02,$01,$26,$22,$80,$66,$66,$04

spr_splat_1
	!byte $00,$00,$00,$12,$24,$01,$00,$00,$46,$a8,$24,$c6,$52

spr_splat_2
	!byte $00,$00,$00,$92,$24,$00,$00,$00,$40,$20,$0c,$20,$48

