!cpu 6502
!to "tab.prg", cbm
; Auto-generated by tools/gentables.py — do not edit
; Staging @ $8000 for copy_tab. Runtime: COSTAB = SINTAB+64.
; Order: alog 512, log 256, sin 320, invzl 128, invzh 128
*= $8000
tab_alog
	!byte $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01
	!byte $01,$01,$01,$02,$02,$02,$02,$02,$02,$02,$02,$02,$02,$02,$02,$02
	!byte $02,$02,$02,$02,$02,$02,$02,$02,$02,$02,$02,$03,$03,$03,$03,$03
	!byte $03,$03,$03,$03,$03,$03,$03,$03,$03,$03,$04,$04,$04,$04,$04,$04
	!byte $04,$04,$04,$04,$04,$04,$05,$05,$05,$05,$05,$05,$05,$05,$05,$06
	!byte $06,$06,$06,$06,$06,$06,$06,$07,$07,$07,$07,$07,$07,$07,$08,$08
	!byte $08,$08,$08,$09,$09,$09,$09,$09,$0a,$0a,$0a,$0a,$0a,$0b,$0b,$0b
	!byte $0b,$0c,$0c,$0c,$0c,$0d,$0d,$0d,$0d,$0e,$0e,$0e,$0f,$0f,$0f,$10
	!byte $10,$10,$11,$11,$11,$12,$12,$13,$13,$13,$14,$14,$15,$15,$16,$16
	!byte $17,$17,$18,$18,$19,$19,$1a,$1a,$1b,$1b,$1c,$1d,$1d,$1e,$1f,$1f
	!byte $20,$21,$21,$22,$23,$24,$24,$25,$26,$27,$28,$29,$29,$2a,$2b,$2c
	!byte $2d,$2e,$2f,$30,$31,$32,$34,$35,$36,$37,$38,$39,$3b,$3c,$3d,$3f
	!byte $40,$41,$43,$44,$46,$47,$49,$4a,$4c,$4e,$4f,$51,$53,$55,$57,$59
	!byte $5b,$5c,$5f,$61,$63,$65,$67,$69,$6c,$6e,$70,$73,$75,$78,$7b,$7d
	!byte $80,$83,$86,$89,$8c,$8f,$92,$95,$98,$9c,$9f,$a2,$a6,$aa,$ad,$b1
	!byte $b5,$b9,$bd,$c1,$c5,$ca,$ce,$d3,$d7,$dc,$e1,$e6,$eb,$f0,$f5,$fb
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
tab_log
	!byte $00,$00,$20,$33,$40,$4a,$53,$5a,$60,$65,$6a,$6f,$73,$76,$7a,$7d
	!byte $80,$83,$85,$88,$8a,$8d,$8f,$91,$93,$95,$96,$98,$9a,$9b,$9d,$9f
	!byte $a0,$a1,$a3,$a4,$a5,$a7,$a8,$a9,$aa,$ab,$ad,$ae,$af,$b0,$b1,$b2
	!byte $b3,$b4,$b5,$b6,$b6,$b7,$b8,$b9,$ba,$bb,$bb,$bc,$bd,$be,$bf,$bf
	!byte $c0,$c1,$c1,$c2,$c3,$c3,$c4,$c5,$c5,$c6,$c7,$c7,$c8,$c9,$c9,$ca
	!byte $ca,$cb,$cb,$cc,$cd,$cd,$ce,$ce,$cf,$cf,$d0,$d0,$d1,$d1,$d2,$d2
	!byte $d3,$d3,$d4,$d4,$d5,$d5,$d6,$d6,$d6,$d7,$d7,$d8,$d8,$d9,$d9,$d9
	!byte $da,$da,$db,$db,$db,$dc,$dc,$dd,$dd,$dd,$de,$de,$df,$df,$df,$e0
	!byte $e0,$e0,$e1,$e1,$e1,$e2,$e2,$e2,$e3,$e3,$e3,$e4,$e4,$e4,$e5,$e5
	!byte $e5,$e6,$e6,$e6,$e7,$e7,$e7,$e8,$e8,$e8,$e9,$e9,$e9,$e9,$ea,$ea
	!byte $ea,$eb,$eb,$eb,$eb,$ec,$ec,$ec,$ed,$ed,$ed,$ed,$ee,$ee,$ee,$ee
	!byte $ef,$ef,$ef,$ef,$f0,$f0,$f0,$f1,$f1,$f1,$f1,$f2,$f2,$f2,$f2,$f2
	!byte $f3,$f3,$f3,$f3,$f4,$f4,$f4,$f4,$f5,$f5,$f5,$f5,$f6,$f6,$f6,$f6
	!byte $f6,$f7,$f7,$f7,$f7,$f8,$f8,$f8,$f8,$f8,$f9,$f9,$f9,$f9,$f9,$fa
	!byte $fa,$fa,$fa,$fa,$fb,$fb,$fb,$fb,$fb,$fc,$fc,$fc,$fc,$fc,$fd,$fd
	!byte $fd,$fd,$fd,$fe,$fe,$fe,$fe,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
tab_sin
	!byte $00,$03,$06,$09,$0c,$10,$13,$16,$19,$1c,$1f,$22,$25,$28,$2b,$2e
	!byte $31,$33,$36,$39,$3c,$3f,$41,$44,$47,$49,$4c,$4e,$51,$53,$55,$58
	!byte $5a,$5c,$5e,$60,$62,$64,$66,$68,$6a,$6b,$6d,$6f,$70,$71,$73,$74
	!byte $75,$76,$78,$79,$7a,$7a,$7b,$7c,$7d,$7d,$7e,$7e,$7e,$7f,$7f,$7f
	!byte $7f,$7f,$7f,$7f,$7e,$7e,$7e,$7d,$7d,$7c,$7b,$7a,$7a,$79,$78,$76
	!byte $75,$74,$73,$71,$70,$6f,$6d,$6b,$6a,$68,$66,$64,$62,$60,$5e,$5c
	!byte $5a,$58,$55,$53,$51,$4e,$4c,$49,$47,$44,$41,$3f,$3c,$39,$36,$33
	!byte $31,$2e,$2b,$28,$25,$22,$1f,$1c,$19,$16,$13,$10,$0c,$09,$06,$03
	!byte $00,$fd,$fa,$f7,$f4,$f0,$ed,$ea,$e7,$e4,$e1,$de,$db,$d8,$d5,$d2
	!byte $cf,$cd,$ca,$c7,$c4,$c1,$bf,$bc,$b9,$b7,$b4,$b2,$af,$ad,$ab,$a8
	!byte $a6,$a4,$a2,$a0,$9e,$9c,$9a,$98,$96,$95,$93,$91,$90,$8f,$8d,$8c
	!byte $8b,$8a,$88,$87,$86,$86,$85,$84,$83,$83,$82,$82,$82,$81,$81,$81
	!byte $81,$81,$81,$81,$82,$82,$82,$83,$83,$84,$85,$86,$86,$87,$88,$8a
	!byte $8b,$8c,$8d,$8f,$90,$91,$93,$95,$96,$98,$9a,$9c,$9e,$a0,$a2,$a4
	!byte $a6,$a8,$ab,$ad,$af,$b2,$b4,$b7,$b9,$bc,$bf,$c1,$c4,$c7,$ca,$cd
	!byte $cf,$d2,$d5,$d8,$db,$de,$e1,$e4,$e7,$ea,$ed,$f0,$f4,$f7,$fa,$fd
	!byte $00,$03,$06,$09,$0c,$10,$13,$16,$19,$1c,$1f,$22,$25,$28,$2b,$2e
	!byte $31,$33,$36,$39,$3c,$3f,$41,$44,$47,$49,$4c,$4e,$51,$53,$55,$58
	!byte $5a,$5c,$5e,$60,$62,$64,$66,$68,$6a,$6b,$6d,$6f,$70,$71,$73,$74
	!byte $75,$76,$78,$79,$7a,$7a,$7b,$7c,$7d,$7d,$7e,$7e,$7e,$7f,$7f,$7f
tab_invzl
	!byte $00,$73,$ec,$6b,$f0,$7b,$0b,$a1,$3c,$dc,$81,$2c,$db,$8f,$48,$05
	!byte $c7,$8d,$57,$26,$f9,$cf,$aa,$89,$6b,$51,$3b,$29,$1a,$0e,$06,$01
	!byte $00,$01,$06,$0e,$18,$26,$37,$4b,$61,$7a,$96,$b5,$d6,$fa,$20,$49
	!byte $74,$a1,$d1,$04,$38,$6f,$a8,$e4,$21,$60,$a2,$e5,$2b,$73,$bc,$08
	!byte $55,$a4,$f5,$48,$9c,$f3,$4a,$a4,$00,$5c,$bb,$1b,$7d,$e0,$45,$ab
	!byte $13,$7c,$e7,$53,$c1,$30,$a0,$11,$84,$f8,$6e,$e5,$5d,$d6,$50,$cc
	!byte $49,$c7,$46,$c6,$47,$ca,$4d,$d2,$58,$df,$66,$ef,$79,$04,$90,$1c
	!byte $aa,$39,$c8,$59,$eb,$7d,$10,$a4,$39,$cf,$66,$fd,$96,$2f,$c9,$64
tab_invzh
	!byte $c8,$c6,$c4,$c3,$c1,$c0,$bf,$bd,$bc,$ba,$b9,$b8,$b6,$b5,$b4,$b3
	!byte $b1,$b0,$af,$ae,$ac,$ab,$aa,$a9,$a8,$a7,$a6,$a5,$a4,$a3,$a2,$a1
	!byte $a0,$9f,$9e,$9d,$9c,$9b,$9a,$99,$98,$97,$96,$95,$94,$93,$93,$92
	!byte $91,$90,$8f,$8f,$8e,$8d,$8c,$8b,$8b,$8a,$89,$88,$88,$87,$86,$86
	!byte $85,$84,$83,$83,$82,$81,$81,$80,$80,$7f,$7e,$7e,$7d,$7c,$7c,$7b
	!byte $7b,$7a,$79,$79,$78,$78,$77,$77,$76,$75,$75,$74,$74,$73,$73,$72
	!byte $72,$71,$71,$70,$70,$6f,$6f,$6e,$6e,$6d,$6d,$6c,$6c,$6c,$6b,$6b
	!byte $6a,$6a,$69,$69,$68,$68,$68,$67,$67,$66,$66,$65,$65,$65,$64,$64
